import { NextRequest, NextResponse } from 'next/server';
import { getSupabaseAdmin } from '@/app/api/_lib/supabase';
import { adminCorsHeaders, requireAdminRequest } from '@/app/api/_lib/admin-guard';


const corsHeaders = adminCorsHeaders;

export async function OPTIONS() {
  return new NextResponse(null, { status: 200, headers: corsHeaders });
}

// POST /api/admin/seed-job-roles — Seed 150 job roles
// Schema: role_name, category, mbti_best TEXT[], disc_prefs TEXT[], big_five_avg JSONB
export async function POST(req: NextRequest) {
  const unauthorized = requireAdminRequest(req);
  if (unauthorized) return unauthorized;

  try {
    const jobRolesData = [
      { role_number: 1, role_name: 'Software Engineer', category: 'Tech & Business', mbti_best: ['ENTP', 'INTP', 'ENTJ'], disc_prefs: ['C', 'D'], big_five_avg: {"O": 3, "C": 4, "E": 2, "A": 3, "N": 2}, salary_min: 65000, salary_max: 165000, growth_rate: 'Fast' },
      { role_number: 2, role_name: 'Data Scientist', category: 'Tech & Business', mbti_best: ['INTP', 'ENTP', 'INTJ'], disc_prefs: ['C', 'D'], big_five_avg: {"O": 4, "C": 4, "E": 2, "A": 2, "N": 2}, salary_min: 70000, salary_max: 175000, growth_rate: 'Fast' },
      { role_number: 3, role_name: 'Product Manager', category: 'Tech & Business', mbti_best: ['ENTP', 'INTP', 'ENTJ'], disc_prefs: ['D', 'I'], big_five_avg: {"O": 4, "C": 4, "E": 4, "A": 3, "N": 2}, salary_min: 85000, salary_max: 200000, growth_rate: 'Fast' },
      { role_number: 4, role_name: 'UX Designer', category: 'Creative & Arts', mbti_best: ['ENFP', 'INFP', 'ENFJ'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 5, "C": 3, "E": 3, "A": 4, "N": 2}, salary_min: 55000, salary_max: 140000, growth_rate: 'Moderate' },
      { role_number: 5, role_name: 'DevOps Engineer', category: 'Tech & Business', mbti_best: ['INTP', 'ENTP', 'INTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 3, "C": 5, "E": 2, "A": 2, "N": 2}, salary_min: 75000, salary_max: 170000, growth_rate: 'Fast' },
      { role_number: 6, role_name: 'Frontend Developer', category: 'Tech & Business', mbti_best: ['ENTP', 'INTP', 'ENTJ'], disc_prefs: ['I', 'C'], big_five_avg: {"O": 4, "C": 3, "E": 3, "A": 3, "N": 2}, salary_min: 55000, salary_max: 140000, growth_rate: 'Fast' },
      { role_number: 7, role_name: 'Backend Developer', category: 'Tech & Business', mbti_best: ['INTP', 'ENTP', 'INTJ'], disc_prefs: ['C', 'D'], big_five_avg: {"O": 3, "C": 4, "E": 2, "A": 2, "N": 2}, salary_min: 65000, salary_max: 165000, growth_rate: 'Fast' },
      { role_number: 8, role_name: 'Mobile Developer', category: 'Tech & Business', mbti_best: ['ENTP', 'INTP', 'ENTJ'], disc_prefs: ['I', 'C'], big_five_avg: {"O": 4, "C": 3, "E": 3, "A": 3, "N": 2}, salary_min: 60000, salary_max: 155000, growth_rate: 'Fast' },
      { role_number: 9, role_name: 'Machine Learning Engineer', category: 'Tech & Business', mbti_best: ['INTP', 'ENTP', 'INTJ'], disc_prefs: ['C', 'D'], big_five_avg: {"O": 5, "C": 4, "E": 2, "A": 2, "N": 2}, salary_min: 90000, salary_max: 220000, growth_rate: 'Fast' },
      { role_number: 10, role_name: 'QA Engineer', category: 'Tech & Business', mbti_best: ['ISTJ', 'ISFJ', 'INTJ'], disc_prefs: ['C', 'S'], big_five_avg: {"O": 3, "C": 5, "E": 2, "A": 3, "N": 2}, salary_min: 45000, salary_max: 110000, growth_rate: 'Stable' },
      { role_number: 11, role_name: 'Systems Architect', category: 'Tech & Business', mbti_best: ['INTJ', 'ENTJ', 'INTP'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 4, "C": 5, "E": 2, "A": 2, "N": 2}, salary_min: 110000, salary_max: 230000, growth_rate: 'Fast' },
      { role_number: 12, role_name: 'Cloud Engineer', category: 'Tech & Business', mbti_best: ['INTP', 'ENTP', 'INTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 3, "C": 4, "E": 2, "A": 2, "N": 2}, salary_min: 75000, salary_max: 175000, growth_rate: 'Fast' },
      { role_number: 13, role_name: 'Cybersecurity Analyst', category: 'Tech & Business', mbti_best: ['INTJ', 'ISTJ', 'ENTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 3, "C": 4, "E": 2, "A": 2, "N": 3}, salary_min: 65000, salary_max: 150000, growth_rate: 'Fast' },
      { role_number: 14, role_name: 'Game Developer', category: 'Creative & Arts', mbti_best: ['ENFP', 'ENTP', 'INFP'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 5, "C": 3, "E": 3, "A": 3, "N": 2}, salary_min: 45000, salary_max: 135000, growth_rate: 'Moderate' },
      { role_number: 15, role_name: 'Blockchain Developer', category: 'Tech & Business', mbti_best: ['INTP', 'ENTP', 'INTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 4, "C": 4, "E": 2, "A": 2, "N": 2}, salary_min: 70000, salary_max: 180000, growth_rate: 'Moderate' },
      { role_number: 16, role_name: 'IT Project Manager', category: 'Tech & Business', mbti_best: ['ENTJ', 'ESTJ', 'ENFJ'], disc_prefs: ['D', 'I'], big_five_avg: {"O": 3, "C": 5, "E": 4, "A": 3, "N": 2}, salary_min: 70000, salary_max: 165000, growth_rate: 'Fast' },
      { role_number: 17, role_name: 'Technical Writer', category: 'Tech & Business', mbti_best: ['INTJ', 'ISTJ', 'INFJ'], disc_prefs: ['C', 'S'], big_five_avg: {"O": 4, "C": 4, "E": 2, "A": 3, "N": 2}, salary_min: 45000, salary_max: 110000, growth_rate: 'Stable' },
      { role_number: 18, role_name: 'Site Reliability Engineer', category: 'Tech & Business', mbti_best: ['INTP', 'ENTP', 'INTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 3, "C": 5, "E": 2, "A": 2, "N": 2}, salary_min: 80000, salary_max: 190000, growth_rate: 'Fast' },
      { role_number: 19, role_name: 'Database Administrator', category: 'Tech & Business', mbti_best: ['ISTJ', 'INTJ', 'ISFJ'], disc_prefs: ['C', 'S'], big_five_avg: {"O": 3, "C": 5, "E": 2, "A": 2, "N": 2}, salary_min: 60000, salary_max: 145000, growth_rate: 'Stable' },
      { role_number: 20, role_name: 'Embedded Systems Engineer', category: 'Tech & Business', mbti_best: ['INTP', 'ISTJ', 'INTJ'], disc_prefs: ['C', 'D'], big_five_avg: {"O": 3, "C": 4, "E": 2, "A": 2, "N": 2}, salary_min: 65000, salary_max: 160000, growth_rate: 'Stable' },
      { role_number: 21, role_name: 'Network Engineer', category: 'Tech & Business', mbti_best: ['ISTJ', 'INTJ', 'ISFJ'], disc_prefs: ['C', 'S'], big_five_avg: {"O": 3, "C": 4, "E": 2, "A": 3, "N": 2}, salary_min: 50000, salary_max: 120000, growth_rate: 'Stable' },
      { role_number: 22, role_name: 'Solutions Architect', category: 'Tech & Business', mbti_best: ['INTJ', 'ENTJ', 'INTP'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 4, "C": 4, "E": 3, "A": 3, "N": 2}, salary_min: 100000, salary_max: 210000, growth_rate: 'Fast' },
      { role_number: 23, role_name: 'Release Manager', category: 'Tech & Business', mbti_best: ['ENTJ', 'ESTJ', 'ISTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 3, "C": 5, "E": 3, "A": 3, "N": 2}, salary_min: 70000, salary_max: 160000, growth_rate: 'Fast' },
      { role_number: 24, role_name: 'Scrum Master', category: 'Tech & Business', mbti_best: ['ENFJ', 'ESFJ', 'ENTJ'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 3, "C": 4, "E": 4, "A": 4, "N": 2}, salary_min: 60000, salary_max: 140000, growth_rate: 'Fast' },
      { role_number: 25, role_name: 'Technical Lead', category: 'Tech & Business', mbti_best: ['ENTJ', 'INTJ', 'ESTJ'], disc_prefs: ['D', 'I'], big_five_avg: {"O": 4, "C": 4, "E": 4, "A": 3, "N": 2}, salary_min: 110000, salary_max: 240000, growth_rate: 'Fast' },
      { role_number: 26, role_name: 'AI Research Scientist', category: 'Tech & Business', mbti_best: ['INTP', 'INTJ', 'ENTP'], disc_prefs: ['C', 'D'], big_five_avg: {"O": 5, "C": 4, "E": 2, "A": 2, "N": 2}, salary_min: 100000, salary_max: 250000, growth_rate: 'Fast' },
      { role_number: 27, role_name: 'Computer Vision Engineer', category: 'Tech & Business', mbti_best: ['INTP', 'INTJ', 'ENTP'], disc_prefs: ['C', 'D'], big_five_avg: {"O": 4, "C": 4, "E": 2, "A": 2, "N": 2}, salary_min: 85000, salary_max: 200000, growth_rate: 'Fast' },
      { role_number: 28, role_name: 'NLP Engineer', category: 'Tech & Business', mbti_best: ['INTP', 'INTJ', 'ENTP'], disc_prefs: ['C', 'D'], big_five_avg: {"O": 5, "C": 4, "E": 2, "A": 2, "N": 2}, salary_min: 90000, salary_max: 210000, growth_rate: 'Fast' },
      { role_number: 29, role_name: 'Platform Engineer', category: 'Tech & Business', mbti_best: ['INTP', 'ENTP', 'INTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 4, "C": 4, "E": 2, "A": 2, "N": 2}, salary_min: 80000, salary_max: 185000, growth_rate: 'Fast' },
      { role_number: 30, role_name: 'Security Engineer', category: 'Tech & Business', mbti_best: ['INTJ', 'ISTJ', 'ENTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 3, "C": 4, "E": 2, "A": 2, "N": 3}, salary_min: 70000, salary_max: 170000, growth_rate: 'Fast' },
      { role_number: 31, role_name: 'Physician', category: 'Healthcare', mbti_best: ['ISFJ', 'ESFJ', 'ISTJ'], disc_prefs: ['C', 'S'], big_five_avg: {"O": 3, "C": 5, "E": 3, "A": 5, "N": 2}, salary_min: 150000, salary_max: 400000, growth_rate: 'Fast' },
      { role_number: 32, role_name: 'Surgeon', category: 'Healthcare', mbti_best: ['ISTJ', 'INTJ', 'ESTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 3, "C": 5, "E": 2, "A": 3, "N": 2}, salary_min: 200000, salary_max: 500000, growth_rate: 'Fast' },
      { role_number: 33, role_name: 'Registered Nurse', category: 'Healthcare', mbti_best: ['ESFJ', 'ISFJ', 'ENFJ'], disc_prefs: ['S', 'I'], big_five_avg: {"O": 3, "C": 4, "E": 4, "A": 5, "N": 3}, salary_min: 55000, salary_max: 110000, growth_rate: 'Fast' },
      { role_number: 34, role_name: 'Pharmacist', category: 'Healthcare', mbti_best: ['ISTJ', 'ISFJ', 'INTJ'], disc_prefs: ['C', 'S'], big_five_avg: {"O": 3, "C": 4, "E": 3, "A": 3, "N": 2}, salary_min: 100000, salary_max: 150000, growth_rate: 'Stable' },
      { role_number: 35, role_name: 'Physical Therapist', category: 'Healthcare', mbti_best: ['ENFJ', 'ESFJ', 'INFJ'], disc_prefs: ['S', 'I'], big_five_avg: {"O": 3, "C": 3, "E": 4, "A": 5, "N": 2}, salary_min: 60000, salary_max: 110000, growth_rate: 'Fast' },
      { role_number: 36, role_name: 'Dentist', category: 'Healthcare', mbti_best: ['ISTJ', 'ESTJ', 'ISFJ'], disc_prefs: ['C', 'S'], big_five_avg: {"O": 3, "C": 4, "E": 3, "A": 3, "N": 2}, salary_min: 130000, salary_max: 280000, growth_rate: 'Fast' },
      { role_number: 37, role_name: 'Clinical Psychologist', category: 'Healthcare', mbti_best: ['INFJ', 'INFP', 'ENFJ'], disc_prefs: ['S', 'I'], big_five_avg: {"O": 4, "C": 3, "E": 3, "A": 5, "N": 4}, salary_min: 70000, salary_max: 150000, growth_rate: 'Moderate' },
      { role_number: 38, role_name: 'Healthcare Administrator', category: 'Healthcare', mbti_best: ['ENTJ', 'ESTJ', 'ENFJ'], disc_prefs: ['D', 'I'], big_five_avg: {"O": 3, "C": 4, "E": 4, "A": 3, "N": 2}, salary_min: 65000, salary_max: 160000, growth_rate: 'Fast' },
      { role_number: 39, role_name: 'Medical Laboratory Scientist', category: 'Healthcare', mbti_best: ['ISTJ', 'INTJ', 'ISFJ'], disc_prefs: ['C', 'S'], big_five_avg: {"O": 3, "C": 4, "E": 2, "A": 3, "N": 2}, salary_min: 45000, salary_max: 95000, growth_rate: 'Stable' },
      { role_number: 40, role_name: 'Occupational Therapist', category: 'Healthcare', mbti_best: ['ENFJ', 'INFJ', 'ESFJ'], disc_prefs: ['S', 'I'], big_five_avg: {"O": 4, "C": 3, "E": 4, "A": 5, "N": 2}, salary_min: 60000, salary_max: 110000, growth_rate: 'Fast' },
      { role_number: 41, role_name: 'Veterinarian', category: 'Healthcare', mbti_best: ['ENFJ', 'INFJ', 'ESFJ'], disc_prefs: ['S', 'I'], big_five_avg: {"O": 4, "C": 4, "E": 4, "A": 5, "N": 2}, salary_min: 70000, salary_max: 160000, growth_rate: 'Fast' },
      { role_number: 42, role_name: 'Speech-Language Pathologist', category: 'Healthcare', mbti_best: ['ENFJ', 'INFJ', 'ESFJ'], disc_prefs: ['S', 'I'], big_five_avg: {"O": 4, "C": 3, "E": 4, "A": 5, "N": 2}, salary_min: 55000, salary_max: 100000, growth_rate: 'Fast' },
      { role_number: 43, role_name: 'Radiologic Technologist', category: 'Healthcare', mbti_best: ['ISFJ', 'ISTJ', 'ESFJ'], disc_prefs: ['C', 'S'], big_five_avg: {"O": 3, "C": 4, "E": 3, "A": 3, "N": 2}, salary_min: 45000, salary_max: 90000, growth_rate: 'Stable' },
      { role_number: 44, role_name: 'Dental Hygienist', category: 'Healthcare', mbti_best: ['ESFJ', 'ISFJ', 'ENFJ'], disc_prefs: ['S', 'I'], big_five_avg: {"O": 3, "C": 3, "E": 4, "A": 4, "N": 2}, salary_min: 60000, salary_max: 100000, growth_rate: 'Fast' },
      { role_number: 45, role_name: 'Genetic Counselor', category: 'Healthcare', mbti_best: ['INFJ', 'ENFJ', 'INFP'], disc_prefs: ['S', 'I'], big_five_avg: {"O": 4, "C": 3, "E": 3, "A": 5, "N": 3}, salary_min: 55000, salary_max: 100000, growth_rate: 'Moderate' },
      { role_number: 46, role_name: 'Anesthesiologist', category: 'Healthcare', mbti_best: ['ISTJ', 'INTJ', 'ESTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 3, "C": 5, "E": 2, "A": 3, "N": 2}, salary_min: 250000, salary_max: 550000, growth_rate: 'Fast' },
      { role_number: 47, role_name: 'Cardiologist', category: 'Healthcare', mbti_best: ['ISTJ', 'INTJ', 'ESTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 3, "C": 4, "E": 3, "A": 3, "N": 2}, salary_min: 200000, salary_max: 480000, growth_rate: 'Fast' },
      { role_number: 48, role_name: 'Pediatrician', category: 'Healthcare', mbti_best: ['ENFJ', 'ESFJ', 'INFJ'], disc_prefs: ['S', 'I'], big_five_avg: {"O": 4, "C": 4, "E": 4, "A": 5, "N": 2}, salary_min: 130000, salary_max: 280000, growth_rate: 'Fast' },
      { role_number: 49, role_name: 'Psychiatrist', category: 'Healthcare', mbti_best: ['INFJ', 'INTJ', 'ENFJ'], disc_prefs: ['S', 'C'], big_five_avg: {"O": 4, "C": 3, "E": 3, "A": 5, "N": 4}, salary_min: 150000, salary_max: 300000, growth_rate: 'Moderate' },
      { role_number: 50, role_name: 'Emergency Medicine Physician', category: 'Healthcare', mbti_best: ['ENTJ', 'ESTJ', 'ISTJ'], disc_prefs: ['D', 'I'], big_five_avg: {"O": 3, "C": 4, "E": 4, "A": 3, "N": 3}, salary_min: 200000, salary_max: 450000, growth_rate: 'Fast' },
      { role_number: 51, role_name: 'Graphic Designer', category: 'Creative & Arts', mbti_best: ['ENFP', 'INFP', 'ESFP'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 5, "C": 3, "E": 3, "A": 3, "N": 2}, salary_min: 38000, salary_max: 110000, growth_rate: 'Moderate' },
      { role_number: 52, role_name: 'UX Designer', category: 'Creative & Arts', mbti_best: ['ENFP', 'INFP', 'ENFJ'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 5, "C": 3, "E": 3, "A": 4, "N": 2}, salary_min: 55000, salary_max: 140000, growth_rate: 'Moderate' },
      { role_number: 53, role_name: 'Illustrator', category: 'Creative & Arts', mbti_best: ['INFP', 'ISFP', 'ENFP'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 5, "C": 3, "E": 2, "A": 3, "N": 3}, salary_min: 30000, salary_max: 95000, growth_rate: 'Moderate' },
      { role_number: 54, role_name: 'Art Director', category: 'Creative & Arts', mbti_best: ['ENTP', 'ENFJ', 'ENTJ'], disc_prefs: ['I', 'D'], big_five_avg: {"O": 5, "C": 4, "E": 4, "A": 3, "N": 2}, salary_min: 65000, salary_max: 180000, growth_rate: 'Moderate' },
      { role_number: 55, role_name: 'Photographer', category: 'Creative & Arts', mbti_best: ['INFP', 'ISFP', 'ENFP'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 5, "C": 3, "E": 3, "A": 3, "N": 2}, salary_min: 28000, salary_max: 90000, growth_rate: 'Moderate' },
      { role_number: 56, role_name: 'Video Editor', category: 'Creative & Arts', mbti_best: ['INFP', 'INTP', 'ISFP'], disc_prefs: ['C', 'I'], big_five_avg: {"O": 4, "C": 3, "E": 2, "A": 3, "N": 2}, salary_min: 35000, salary_max: 95000, growth_rate: 'Moderate' },
      { role_number: 57, role_name: 'Motion Graphics Designer', category: 'Creative & Arts', mbti_best: ['ENFP', 'ENTP', 'INFP'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 5, "C": 3, "E": 3, "A": 3, "N": 2}, salary_min: 45000, salary_max: 120000, growth_rate: 'Moderate' },
      { role_number: 58, role_name: 'Creative Director', category: 'Creative & Arts', mbti_best: ['ENTP', 'ENTJ', 'ENFJ'], disc_prefs: ['I', 'D'], big_five_avg: {"O": 5, "C": 4, "E": 5, "A": 3, "N": 2}, salary_min: 80000, salary_max: 220000, growth_rate: 'Moderate' },
      { role_number: 59, role_name: 'Interior Designer', category: 'Creative & Arts', mbti_best: ['ENFP', 'INFP', 'ESFJ'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 5, "C": 3, "E": 3, "A": 4, "N": 2}, salary_min: 38000, salary_max: 115000, growth_rate: 'Moderate' },
      { role_number: 60, role_name: 'Fashion Designer', category: 'Creative & Arts', mbti_best: ['ENFP', 'INFP', 'ISFP'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 5, "C": 3, "E": 3, "A": 3, "N": 2}, salary_min: 35000, salary_max: 135000, growth_rate: 'Moderate' },
      { role_number: 61, role_name: 'Product Designer', category: 'Creative & Arts', mbti_best: ['ENFP', 'ENTP', 'INFP'], disc_prefs: ['I', 'D'], big_five_avg: {"O": 5, "C": 4, "E": 3, "A": 3, "N": 2}, salary_min: 60000, salary_max: 150000, growth_rate: 'Moderate' },
      { role_number: 62, role_name: 'Brand Designer', category: 'Creative & Arts', mbti_best: ['ENFP', 'ENTP', 'ENFJ'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 5, "C": 3, "E": 4, "A": 3, "N": 2}, salary_min: 45000, salary_max: 130000, growth_rate: 'Moderate' },
      { role_number: 63, role_name: 'UI Designer', category: 'Creative & Arts', mbti_best: ['ENFP', 'INFP', 'ENTP'], disc_prefs: ['I', 'C'], big_five_avg: {"O": 5, "C": 3, "E": 3, "A": 3, "N": 2}, salary_min: 55000, salary_max: 140000, growth_rate: 'Moderate' },
      { role_number: 64, role_name: 'Web Designer', category: 'Creative & Arts', mbti_best: ['ENFP', 'INFP', 'ISFP'], disc_prefs: ['I', 'C'], big_five_avg: {"O": 4, "C": 3, "E": 3, "A": 3, "N": 2}, salary_min: 38000, salary_max: 110000, growth_rate: 'Moderate' },
      { role_number: 65, role_name: 'Animator', category: 'Creative & Arts', mbti_best: ['ENFP', 'ENTP', 'ISFP'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 5, "C": 3, "E": 3, "A": 3, "N": 2}, salary_min: 40000, salary_max: 125000, growth_rate: 'Moderate' },
      { role_number: 66, role_name: '3D Artist', category: 'Creative & Arts', mbti_best: ['INFP', 'INTP', 'ISFP'], disc_prefs: ['I', 'C'], big_five_avg: {"O": 4, "C": 3, "E": 2, "A": 3, "N": 2}, salary_min: 40000, salary_max: 120000, growth_rate: 'Moderate' },
      { role_number: 67, role_name: 'Visual Effects Artist', category: 'Creative & Arts', mbti_best: ['INFP', 'INTP', 'ISFP'], disc_prefs: ['C', 'I'], big_five_avg: {"O": 4, "C": 3, "E": 2, "A": 2, "N": 2}, salary_min: 45000, salary_max: 130000, growth_rate: 'Moderate' },
      { role_number: 68, role_name: 'Game Artist', category: 'Creative & Arts', mbti_best: ['ENFP', 'INFP', 'ISFP'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 5, "C": 3, "E": 3, "A": 3, "N": 2}, salary_min: 40000, salary_max: 115000, growth_rate: 'Moderate' },
      { role_number: 69, role_name: 'Packaging Designer', category: 'Creative & Arts', mbti_best: ['ENFP', 'INFP', 'ISFP'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 4, "C": 3, "E": 3, "A": 3, "N": 2}, salary_min: 38000, salary_max: 100000, growth_rate: 'Moderate' },
      { role_number: 70, role_name: 'UX Researcher', category: 'Creative & Arts', mbti_best: ['INFJ', 'INFP', 'ENFJ'], disc_prefs: ['S', 'C'], big_five_avg: {"O": 4, "C": 4, "E": 3, "A": 4, "N": 2}, salary_min: 60000, salary_max: 135000, growth_rate: 'Moderate' },
      { role_number: 71, role_name: 'Investment Banker', category: 'Tech & Business', mbti_best: ['ENTJ', 'ESTJ', 'INTJ'], disc_prefs: ['D', 'I'], big_five_avg: {"O": 3, "C": 5, "E": 4, "A": 2, "N": 3}, salary_min: 100000, salary_max: 500000, growth_rate: 'Fast' },
      { role_number: 72, role_name: 'Management Consultant', category: 'Tech & Business', mbti_best: ['ENTJ', 'ESTJ', 'INTJ'], disc_prefs: ['D', 'I'], big_five_avg: {"O": 4, "C": 4, "E": 4, "A": 3, "N": 2}, salary_min: 85000, salary_max: 250000, growth_rate: 'Fast' },
      { role_number: 73, role_name: 'Financial Analyst', category: 'Tech & Business', mbti_best: ['INTJ', 'ISTJ', 'INTP'], disc_prefs: ['C', 'D'], big_five_avg: {"O": 3, "C": 5, "E": 2, "A": 2, "N": 2}, salary_min: 55000, salary_max: 145000, growth_rate: 'Fast' },
      { role_number: 74, role_name: 'Accountant', category: 'Tech & Business', mbti_best: ['ISTJ', 'ESTJ', 'INTJ'], disc_prefs: ['C', 'S'], big_five_avg: {"O": 3, "C": 5, "E": 2, "A": 3, "N": 2}, salary_min: 50000, salary_max: 130000, growth_rate: 'Stable' },
      { role_number: 75, role_name: 'Marketing Manager', category: 'Tech & Business', mbti_best: ['ENTJ', 'ENFJ', 'ESTJ'], disc_prefs: ['I', 'D'], big_five_avg: {"O": 4, "C": 4, "E": 5, "A": 3, "N": 2}, salary_min: 60000, salary_max: 200000, growth_rate: 'Fast' },
      { role_number: 76, role_name: 'Sales Manager', category: 'Tech & Business', mbti_best: ['ENTJ', 'ESTJ', 'ENFJ'], disc_prefs: ['D', 'I'], big_five_avg: {"O": 3, "C": 4, "E": 5, "A": 3, "N": 2}, salary_min: 55000, salary_max: 220000, growth_rate: 'Fast' },
      { role_number: 77, role_name: 'Human Resources Manager', category: 'Tech & Business', mbti_best: ['ENFJ', 'ESFJ', 'ENTJ'], disc_prefs: ['S', 'I'], big_five_avg: {"O": 3, "C": 4, "E": 4, "A": 5, "N": 2}, salary_min: 55000, salary_max: 160000, growth_rate: 'Fast' },
      { role_number: 78, role_name: 'Operations Manager', category: 'Tech & Business', mbti_best: ['ENTJ', 'ESTJ', 'INTJ'], disc_prefs: ['D', 'S'], big_five_avg: {"O": 3, "C": 5, "E": 4, "A": 3, "N": 2}, salary_min: 60000, salary_max: 175000, growth_rate: 'Fast' },
      { role_number: 79, role_name: 'CEO', category: 'Tech & Business', mbti_best: ['ENTJ', 'ESTJ', 'INTJ'], disc_prefs: ['D', 'I'], big_five_avg: {"O": 5, "C": 5, "E": 5, "A": 3, "N": 2}, salary_min: 150000, salary_max: 1000000, growth_rate: 'Fast' },
      { role_number: 80, role_name: 'Entrepreneur', category: 'Tech & Business', mbti_best: ['ENTJ', 'ENTP', 'ENFJ'], disc_prefs: ['D', 'I'], big_five_avg: {"O": 5, "C": 4, "E": 5, "A": 2, "N": 3}, salary_min: 0, salary_max: 2000000, growth_rate: 'Moderate' },
      { role_number: 81, role_name: 'Product Manager', category: 'Tech & Business', mbti_best: ['ENTJ', 'ENTP', 'ENFJ'], disc_prefs: ['D', 'I'], big_five_avg: {"O": 4, "C": 4, "E": 4, "A": 3, "N": 2}, salary_min: 85000, salary_max: 220000, growth_rate: 'Fast' },
      { role_number: 82, role_name: 'Project Manager', category: 'Tech & Business', mbti_best: ['ENTJ', 'ESTJ', 'ENFJ'], disc_prefs: ['D', 'S'], big_five_avg: {"O": 3, "C": 5, "E": 4, "A": 3, "N": 2}, salary_min: 60000, salary_max: 170000, growth_rate: 'Fast' },
      { role_number: 83, role_name: 'Supply Chain Manager', category: 'Tech & Business', mbti_best: ['ENTJ', 'ESTJ', 'ISTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 3, "C": 5, "E": 3, "A": 3, "N": 2}, salary_min: 60000, salary_max: 160000, growth_rate: 'Stable' },
      { role_number: 84, role_name: 'Risk Manager', category: 'Tech & Business', mbti_best: ['INTJ', 'ISTJ', 'ENTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 3, "C": 5, "E": 2, "A": 2, "N": 3}, salary_min: 70000, salary_max: 190000, growth_rate: 'Stable' },
      { role_number: 85, role_name: 'Business Analyst', category: 'Tech & Business', mbti_best: ['INTJ', 'ISTJ', 'ENTJ'], disc_prefs: ['C', 'I'], big_five_avg: {"O": 4, "C": 4, "E": 3, "A": 3, "N": 2}, salary_min: 55000, salary_max: 140000, growth_rate: 'Fast' },
      { role_number: 86, role_name: 'Actuary', category: 'Tech & Business', mbti_best: ['ISTJ', 'INTJ', 'INTP'], disc_prefs: ['C', 'D'], big_five_avg: {"O": 3, "C": 5, "E": 2, "A": 2, "N": 2}, salary_min: 65000, salary_max: 180000, growth_rate: 'Stable' },
      { role_number: 87, role_name: 'Tax Attorney', category: 'Tech & Business', mbti_best: ['ISTJ', 'INTJ', 'ESTJ'], disc_prefs: ['C', 'D'], big_five_avg: {"O": 3, "C": 5, "E": 3, "A": 3, "N": 2}, salary_min: 70000, salary_max: 250000, growth_rate: 'Stable' },
      { role_number: 88, role_name: 'Compliance Officer', category: 'Tech & Business', mbti_best: ['ISTJ', 'ESTJ', 'INTJ'], disc_prefs: ['C', 'S'], big_five_avg: {"O": 3, "C": 5, "E": 2, "A": 3, "N": 2}, salary_min: 60000, salary_max: 155000, growth_rate: 'Stable' },
      { role_number: 89, role_name: 'Venture Capitalist', category: 'Tech & Business', mbti_best: ['ENTJ', 'INTJ', 'ENTP'], disc_prefs: ['D', 'I'], big_five_avg: {"O": 5, "C": 4, "E": 4, "A": 2, "N": 2}, salary_min: 120000, salary_max: 1000000, growth_rate: 'Moderate' },
      { role_number: 90, role_name: 'Private Equity Analyst', category: 'Tech & Business', mbti_best: ['INTJ', 'ISTJ', 'ENTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 3, "C": 5, "E": 2, "A": 2, "N": 2}, salary_min: 80000, salary_max: 300000, growth_rate: 'Fast' },
      { role_number: 91, role_name: 'Professor', category: 'Tech & Business', mbti_best: ['INTJ', 'INFJ', 'ENTJ'], disc_prefs: ['C', 'S'], big_five_avg: {"O": 5, "C": 4, "E": 3, "A": 4, "N": 2}, salary_min: 60000, salary_max: 220000, growth_rate: 'Stable' },
      { role_number: 92, role_name: 'High School Teacher', category: 'Tech & Business', mbti_best: ['ENFJ', 'ESFJ', 'ENTJ'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 4, "C": 4, "E": 5, "A": 5, "N": 2}, salary_min: 45000, salary_max: 100000, growth_rate: 'Stable' },
      { role_number: 93, role_name: 'Elementary School Teacher', category: 'Tech & Business', mbti_best: ['ESFJ', 'ENFJ', 'ISFJ'], disc_prefs: ['S', 'I'], big_five_avg: {"O": 4, "C": 4, "E": 5, "A": 5, "N": 2}, salary_min: 42000, salary_max: 90000, growth_rate: 'Stable' },
      { role_number: 94, role_name: 'Special Education Teacher', category: 'Tech & Business', mbti_best: ['ENFJ', 'ESFJ', 'INFJ'], disc_prefs: ['S', 'I'], big_five_avg: {"O": 4, "C": 4, "E": 4, "A": 5, "N": 3}, salary_min: 45000, salary_max: 95000, growth_rate: 'Stable' },
      { role_number: 95, role_name: 'Education Administrator', category: 'Tech & Business', mbti_best: ['ENTJ', 'ESTJ', 'ENFJ'], disc_prefs: ['D', 'I'], big_five_avg: {"O": 4, "C": 4, "E": 4, "A": 4, "N": 2}, salary_min: 60000, salary_max: 170000, growth_rate: 'Fast' },
      { role_number: 96, role_name: 'Curriculum Designer', category: 'Tech & Business', mbti_best: ['INTJ', 'INFJ', 'ENTJ'], disc_prefs: ['C', 'I'], big_five_avg: {"O": 5, "C": 4, "E": 3, "A": 4, "N": 2}, salary_min: 50000, salary_max: 115000, growth_rate: 'Moderate' },
      { role_number: 97, role_name: 'Research Scientist', category: 'Tech & Business', mbti_best: ['INTP', 'INTJ', 'INFJ'], disc_prefs: ['C', 'D'], big_five_avg: {"O": 5, "C": 4, "E": 2, "A": 3, "N": 2}, salary_min: 60000, salary_max: 180000, growth_rate: 'Fast' },
      { role_number: 98, role_name: 'Lab Manager', category: 'Tech & Business', mbti_best: ['ENTJ', 'ISTJ', 'ESTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 4, "C": 5, "E": 3, "A": 3, "N": 2}, salary_min: 55000, salary_max: 140000, growth_rate: 'Stable' },
      { role_number: 99, role_name: 'Academic Advisor', category: 'Tech & Business', mbti_best: ['ENFJ', 'INFJ', 'ESFJ'], disc_prefs: ['S', 'I'], big_five_avg: {"O": 4, "C": 3, "E": 4, "A": 5, "N": 2}, salary_min: 40000, salary_max: 90000, growth_rate: 'Stable' },
      { role_number: 100, role_name: 'Tutor', category: 'Tech & Business', mbti_best: ['ENFJ', 'INFP', 'INFJ'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 4, "C": 3, "E": 4, "A": 5, "N": 2}, salary_min: 28000, salary_max: 75000, growth_rate: 'Moderate' },
      { role_number: 101, role_name: 'Corporate Trainer', category: 'Tech & Business', mbti_best: ['ENTJ', 'ENFJ', 'ESTJ'], disc_prefs: ['I', 'D'], big_five_avg: {"O": 4, "C": 4, "E": 5, "A": 4, "N": 2}, salary_min: 50000, salary_max: 135000, growth_rate: 'Fast' },
      { role_number: 102, role_name: 'Instructional Designer', category: 'Tech & Business', mbti_best: ['INTJ', 'INFJ', 'ENFJ'], disc_prefs: ['C', 'I'], big_five_avg: {"O": 5, "C": 4, "E": 3, "A": 4, "N": 2}, salary_min: 50000, salary_max: 110000, growth_rate: 'Moderate' },
      { role_number: 103, role_name: 'Librarian', category: 'Tech & Business', mbti_best: ['ISFJ', 'ISTJ', 'INFJ'], disc_prefs: ['S', 'C'], big_five_avg: {"O": 4, "C": 4, "E": 2, "A": 4, "N": 2}, salary_min: 38000, salary_max: 80000, growth_rate: 'Stable' },
      { role_number: 104, role_name: 'Museum Curator', category: 'Creative & Arts', mbti_best: ['INFJ', 'INTJ', 'INFP'], disc_prefs: ['S', 'C'], big_five_avg: {"O": 5, "C": 4, "E": 3, "A": 4, "N": 2}, salary_min: 40000, salary_max: 110000, growth_rate: 'Moderate' },
      { role_number: 105, role_name: 'Archaeologist', category: 'Tech & Business', mbti_best: ['INTP', 'INFJ', 'ISTJ'], disc_prefs: ['S', 'C'], big_five_avg: {"O": 5, "C": 3, "E": 2, "A": 3, "N": 2}, salary_min: 40000, salary_max: 110000, growth_rate: 'Moderate' },
      { role_number: 106, role_name: 'Hotel Manager', category: 'Service & Hospitality', mbti_best: ['ENTJ', 'ESFJ', 'ESTJ'], disc_prefs: ['I', 'D'], big_five_avg: {"O": 3, "C": 4, "E": 5, "A": 4, "N": 2}, salary_min: 38000, salary_max: 120000, growth_rate: 'Moderate' },
      { role_number: 107, role_name: 'Restaurant Manager', category: 'Service & Hospitality', mbti_best: ['ENTJ', 'ESTJ', 'ESFJ'], disc_prefs: ['D', 'I'], big_five_avg: {"O": 3, "C": 4, "E": 5, "A": 4, "N": 3}, salary_min: 35000, salary_max: 95000, growth_rate: 'Moderate' },
      { role_number: 108, role_name: 'Event Planner', category: 'Service & Hospitality', mbti_best: ['ENTJ', 'ENFJ', 'ESFJ'], disc_prefs: ['I', 'D'], big_five_avg: {"O": 4, "C": 4, "E": 5, "A": 4, "N": 2}, salary_min: 36000, salary_max: 100000, growth_rate: 'Moderate' },
      { role_number: 109, role_name: 'Flight Attendant', category: 'Service & Hospitality', mbti_best: ['ESFJ', 'ENFJ', 'ENTP'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 3, "C": 3, "E": 5, "A": 4, "N": 3}, salary_min: 32000, salary_max: 95000, growth_rate: 'Moderate' },
      { role_number: 110, role_name: 'Tour Guide', category: 'Service & Hospitality', mbti_best: ['ENFJ', 'ESFJ', 'ENTP'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 4, "C": 3, "E": 5, "A": 4, "N": 2}, salary_min: 28000, salary_max: 70000, growth_rate: 'Moderate' },
      { role_number: 111, role_name: 'Customer Success Manager', category: 'Service & Hospitality', mbti_best: ['ENFJ', 'ESFJ', 'ENTJ'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 4, "C": 4, "E": 5, "A": 5, "N": 2}, salary_min: 45000, salary_max: 120000, growth_rate: 'Fast' },
      { role_number: 112, role_name: 'Concierge', category: 'Service & Hospitality', mbti_best: ['ESFJ', 'ENFJ', 'ISFJ'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 4, "C": 3, "E": 5, "A": 5, "N": 2}, salary_min: 28000, salary_max: 65000, growth_rate: 'Moderate' },
      { role_number: 113, role_name: 'Travel Agent', category: 'Service & Hospitality', mbti_best: ['ESFJ', 'ENFJ', 'ISFJ'], disc_prefs: ['S', 'I'], big_five_avg: {"O": 4, "C": 3, "E": 4, "A": 4, "N": 2}, salary_min: 30000, salary_max: 70000, growth_rate: 'Moderate' },
      { role_number: 114, role_name: 'Wedding Planner', category: 'Service & Hospitality', mbti_best: ['ENFJ', 'ESFJ', 'ENTJ'], disc_prefs: ['I', 'D'], big_five_avg: {"O": 4, "C": 4, "E": 4, "A": 4, "N": 2}, salary_min: 35000, salary_max: 120000, growth_rate: 'Moderate' },
      { role_number: 115, role_name: 'Personal Concierge', category: 'Service & Hospitality', mbti_best: ['ESFJ', 'ENFJ', 'ISFJ'], disc_prefs: ['S', 'I'], big_five_avg: {"O": 3, "C": 3, "E": 4, "A": 5, "N": 2}, salary_min: 32000, salary_max: 80000, growth_rate: 'Moderate' },
      { role_number: 116, role_name: 'Electrician', category: 'Trades & Technical', mbti_best: ['ISTJ', 'ESTJ', 'ISFJ'], disc_prefs: ['D', 'S'], big_five_avg: {"O": 3, "C": 4, "E": 3, "A": 3, "N": 2}, salary_min: 42000, salary_max: 95000, growth_rate: 'Stable' },
      { role_number: 117, role_name: 'Plumber', category: 'Trades & Technical', mbti_best: ['ISTJ', 'ESTJ', 'ISFP'], disc_prefs: ['D', 'S'], big_five_avg: {"O": 3, "C": 4, "E": 3, "A": 3, "N": 2}, salary_min: 40000, salary_max: 90000, growth_rate: 'Stable' },
      { role_number: 118, role_name: 'HVAC Technician', category: 'Trades & Technical', mbti_best: ['ISTJ', 'ESTJ', 'ISFJ'], disc_prefs: ['D', 'S'], big_five_avg: {"O": 3, "C": 4, "E": 3, "A": 3, "N": 2}, salary_min: 40000, salary_max: 85000, growth_rate: 'Stable' },
      { role_number: 119, role_name: 'Welder', category: 'Trades & Technical', mbti_best: ['ISTP', 'ISTJ', 'ISFP'], disc_prefs: ['D', 'S'], big_five_avg: {"O": 3, "C": 4, "E": 2, "A": 2, "N": 2}, salary_min: 38000, salary_max: 85000, growth_rate: 'Stable' },
      { role_number: 120, role_name: 'Carpenter', category: 'Trades & Technical', mbti_best: ['ISTP', 'ISTJ', 'ISFP'], disc_prefs: ['D', 'S'], big_five_avg: {"O": 3, "C": 4, "E": 3, "A": 3, "N": 2}, salary_min: 38000, salary_max: 90000, growth_rate: 'Stable' },
      { role_number: 121, role_name: 'Mechanic', category: 'Trades & Technical', mbti_best: ['ISTP', 'ISTJ', 'ISFP'], disc_prefs: ['D', 'S'], big_five_avg: {"O": 3, "C": 4, "E": 3, "A": 3, "N": 2}, salary_min: 35000, salary_max: 85000, growth_rate: 'Stable' },
      { role_number: 122, role_name: 'CNC Machine Operator', category: 'Trades & Technical', mbti_best: ['ISTJ', 'ISTP', 'ISFJ'], disc_prefs: ['C', 'D'], big_five_avg: {"O": 3, "C": 5, "E": 2, "A": 2, "N": 2}, salary_min: 38000, salary_max: 80000, growth_rate: 'Stable' },
      { role_number: 123, role_name: 'Construction Manager', category: 'Trades & Technical', mbti_best: ['ENTJ', 'ESTJ', 'ISTJ'], disc_prefs: ['D', 'S'], big_five_avg: {"O": 3, "C": 5, "E": 4, "A": 3, "N": 2}, salary_min: 60000, salary_max: 170000, growth_rate: 'Stable' },
      { role_number: 124, role_name: 'Civil Engineer', category: 'Trades & Technical', mbti_best: ['ISTJ', 'ESTJ', 'INTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 3, "C": 5, "E": 3, "A": 3, "N": 2}, salary_min: 55000, salary_max: 150000, growth_rate: 'Stable' },
      { role_number: 125, role_name: 'Surveyor', category: 'Trades & Technical', mbti_best: ['ISTJ', 'ESTJ', 'ISFJ'], disc_prefs: ['C', 'S'], big_five_avg: {"O": 3, "C": 4, "E": 3, "A": 3, "N": 2}, salary_min: 45000, salary_max: 100000, growth_rate: 'Stable' },
      { role_number: 126, role_name: 'Lawyer', category: 'Tech & Business', mbti_best: ['INTJ', 'ESTJ', 'ISTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 4, "C": 4, "E": 3, "A": 3, "N": 2}, salary_min: 80000, salary_max: 350000, growth_rate: 'Stable' },
      { role_number: 127, role_name: 'Judge', category: 'Tech & Business', mbti_best: ['ISTJ', 'INTJ', 'ESTJ'], disc_prefs: ['D', 'C'], big_five_avg: {"O": 4, "C": 5, "E": 2, "A": 4, "N": 2}, salary_min: 130000, salary_max: 300000, growth_rate: 'Stable' },
      { role_number: 128, role_name: 'Paralegal', category: 'Tech & Business', mbti_best: ['ISTJ', 'ISFJ', 'INTJ'], disc_prefs: ['C', 'S'], big_five_avg: {"O": 3, "C": 4, "E": 3, "A": 3, "N": 2}, salary_min: 40000, salary_max: 85000, growth_rate: 'Moderate' },
      { role_number: 129, role_name: 'Police Officer', category: 'Trades & Technical', mbti_best: ['ESTJ', 'ESFJ', 'ENTJ'], disc_prefs: ['D', 'S'], big_five_avg: {"O": 3, "C": 4, "E": 4, "A": 3, "N": 3}, salary_min: 45000, salary_max: 110000, growth_rate: 'Stable' },
      { role_number: 130, role_name: 'Firefighter', category: 'Trades & Technical', mbti_best: ['ESTJ', 'ESFJ', 'ENTJ'], disc_prefs: ['D', 'S'], big_five_avg: {"O": 3, "C": 4, "E": 4, "A": 4, "N": 3}, salary_min: 40000, salary_max: 95000, growth_rate: 'Stable' },
      { role_number: 131, role_name: 'Social Worker', category: 'Service & Hospitality', mbti_best: ['ENFJ', 'INFJ', 'ESFJ'], disc_prefs: ['S', 'I'], big_five_avg: {"O": 4, "C": 3, "E": 4, "A": 5, "N": 3}, salary_min: 36000, salary_max: 75000, growth_rate: 'Stable' },
      { role_number: 132, role_name: 'City Planner', category: 'Tech & Business', mbti_best: ['INTJ', 'INFJ', 'ENTJ'], disc_prefs: ['D', 'S'], big_five_avg: {"O": 4, "C": 4, "E": 3, "A": 4, "N": 2}, salary_min: 55000, salary_max: 130000, growth_rate: 'Moderate' },
      { role_number: 133, role_name: 'Policy Analyst', category: 'Tech & Business', mbti_best: ['INTJ', 'INFJ', 'ISTJ'], disc_prefs: ['C', 'S'], big_five_avg: {"O": 4, "C": 4, "E": 3, "A": 4, "N": 2}, salary_min: 55000, salary_max: 140000, growth_rate: 'Moderate' },
      { role_number: 134, role_name: 'Diplomat', category: 'Tech & Business', mbti_best: ['ENFJ', 'INFJ', 'ENTJ'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 4, "C": 4, "E": 4, "A": 4, "N": 2}, salary_min: 70000, salary_max: 200000, growth_rate: 'Moderate' },
      { role_number: 135, role_name: 'Public Relations Specialist', category: 'Tech & Business', mbti_best: ['ENFJ', 'ENTP', 'ESFJ'], disc_prefs: ['I', 'D'], big_five_avg: {"O": 4, "C": 3, "E": 5, "A": 4, "N": 2}, salary_min: 45000, salary_max: 130000, growth_rate: 'Fast' },
      { role_number: 136, role_name: 'Journalist', category: 'Creative & Arts', mbti_best: ['ENFP', 'ENTP', 'INTJ'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 5, "C": 3, "E": 4, "A": 3, "N": 3}, salary_min: 35000, salary_max: 120000, growth_rate: 'Moderate' },
      { role_number: 137, role_name: 'Content Writer', category: 'Creative & Arts', mbti_best: ['INFP', 'ENFP', 'INFJ'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 5, "C": 3, "E": 3, "A": 3, "N": 2}, salary_min: 35000, salary_max: 110000, growth_rate: 'Moderate' },
      { role_number: 138, role_name: 'Technical Writer', category: 'Tech & Business', mbti_best: ['INTJ', 'ISTJ', 'INFJ'], disc_prefs: ['C', 'S'], big_five_avg: {"O": 4, "C": 4, "E": 2, "A": 3, "N": 2}, salary_min: 50000, salary_max: 120000, growth_rate: 'Stable' },
      { role_number: 139, role_name: 'Copywriter', category: 'Creative & Arts', mbti_best: ['ENFP', 'ENTP', 'INFP'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 5, "C": 3, "E": 4, "A": 3, "N": 2}, salary_min: 40000, salary_max: 130000, growth_rate: 'Moderate' },
      { role_number: 140, role_name: 'Social Media Manager', category: 'Creative & Arts', mbti_best: ['ENTP', 'ENFP', 'ESFJ'], disc_prefs: ['I', 'D'], big_five_avg: {"O": 4, "C": 3, "E": 5, "A": 3, "N": 2}, salary_min: 38000, salary_max: 110000, growth_rate: 'Fast' },
      { role_number: 141, role_name: 'Public Relations Manager', category: 'Tech & Business', mbti_best: ['ENTJ', 'ENFJ', 'ENTP'], disc_prefs: ['I', 'D'], big_five_avg: {"O": 4, "C": 4, "E": 5, "A": 4, "N": 2}, salary_min: 65000, salary_max: 180000, growth_rate: 'Fast' },
      { role_number: 142, role_name: 'Broadcast Journalist', category: 'Creative & Arts', mbti_best: ['ENTP', 'ENFJ', 'ENTJ'], disc_prefs: ['I', 'D'], big_five_avg: {"O": 4, "C": 3, "E": 5, "A": 3, "N": 3}, salary_min: 35000, salary_max: 120000, growth_rate: 'Moderate' },
      { role_number: 143, role_name: 'News Producer', category: 'Creative & Arts', mbti_best: ['ENTJ', 'ESTJ', 'ENTP'], disc_prefs: ['D', 'I'], big_five_avg: {"O": 3, "C": 5, "E": 4, "A": 3, "N": 3}, salary_min: 50000, salary_max: 150000, growth_rate: 'Moderate' },
      { role_number: 144, role_name: 'Film Director', category: 'Creative & Arts', mbti_best: ['ENTJ', 'ENTP', 'ENFJ'], disc_prefs: ['D', 'I'], big_five_avg: {"O": 5, "C": 4, "E": 4, "A": 2, "N": 2}, salary_min: 50000, salary_max: 250000, growth_rate: 'Moderate' },
      { role_number: 145, role_name: 'Screenwriter', category: 'Creative & Arts', mbti_best: ['ENFP', 'INFP', 'ENTP'], disc_prefs: ['I', 'S'], big_five_avg: {"O": 5, "C": 3, "E": 3, "A": 3, "N": 3}, salary_min: 30000, salary_max: 220000, growth_rate: 'Moderate' },
      { role_number: 146, role_name: 'Film Editor', category: 'Creative & Arts', mbti_best: ['INTP', 'ISTJ', 'INFP'], disc_prefs: ['C', 'I'], big_five_avg: {"O": 4, "C": 4, "E": 2, "A": 2, "N": 2}, salary_min: 40000, salary_max: 120000, growth_rate: 'Moderate' },
      { role_number: 147, role_name: 'Podcast Host', category: 'Creative & Arts', mbti_best: ['ENTP', 'ENFJ', 'ENTJ'], disc_prefs: ['I', 'D'], big_five_avg: {"O": 4, "C": 3, "E": 5, "A": 3, "N": 2}, salary_min: 28000, salary_max: 180000, growth_rate: 'Moderate' },
      { role_number: 148, role_name: 'YouTube Creator', category: 'Creative & Arts', mbti_best: ['ENTP', 'ENFP', 'ENTJ'], disc_prefs: ['I', 'D'], big_five_avg: {"O": 5, "C": 3, "E": 5, "A": 3, "N": 2}, salary_min: 0, salary_max: 500000, growth_rate: 'Moderate' },
      { role_number: 149, role_name: 'Communications Director', category: 'Tech & Business', mbti_best: ['ENTJ', 'ENFJ', 'ENTP'], disc_prefs: ['I', 'D'], big_five_avg: {"O": 4, "C": 4, "E": 5, "A": 4, "N": 2}, salary_min: 75000, salary_max: 200000, growth_rate: 'Fast' },
      { role_number: 150, role_name: 'Lobbyist', category: 'Tech & Business', mbti_best: ['ENTJ', 'ESTJ', 'INTJ'], disc_prefs: ['D', 'I'], big_five_avg: {"O": 4, "C": 4, "E": 4, "A": 3, "N": 2}, salary_min: 60000, salary_max: 220000, growth_rate: 'Moderate' },
    ];

    const batchSize = 25;
    let totalInserted = 0;

    for (let i = 0; i < jobRolesData.length; i += batchSize) {
      const batch = jobRolesData.slice(i, i + batchSize);
      const { error } = await getSupabaseAdmin().from('job_roles').upsert(batch, { onConflict: 'role_name' });
      if (error) {
        console.error(`[POST /api/admin/seed-job-roles] Error inserting batch ${i / batchSize}:`, error);
      } else {
        totalInserted += batch.length;
      }
    }

    return NextResponse.json({
      success: true,
      message: `Job roles seeded successfully (${totalInserted} roles)`,
      rolesSeeded: totalInserted,
    }, { headers: corsHeaders });
  } catch (error) {
    console.error('[POST /api/admin/seed-job-roles] Error:', error);
    return NextResponse.json(
      { error: 'Failed to seed job roles' },
      { status: 500, headers: corsHeaders }
    );
  }
}
