import { Link } from "wouter";
import { ArrowLeft, ChevronDown } from "lucide-react";
import { useState } from "react";

const FAQ_ITEMS = [
  {
    question: "What is KnowYouRole?",
    answer: "KnowYouRole is a free personality assessment platform that uses three well-established frameworks — Big Five (OCEAN), MBTI, and DISC — to help you discover your personality traits and match them to potential career paths. It's designed for all ages, with tailored experiences for kids, teens, young adults, and adults."
  },
  {
    question: "Is KnowYouRole really free?",
    answer: "Yes! The core personality assessments and career matching features are completely free, with no sign-up required to get started. We offer optional premium features for deeper insights, but the essential experience costs nothing."
  },
  {
    question: "How long does the assessment take?",
    answer: "Most users complete the assessment in 5-10 minutes. The questions are designed to be quick and intuitive — just pick what feels right. There are no trick questions or wrong answers."
  },
  {
    question: "Are the results accurate?",
    answer: "Our assessments are based on well-validated psychological frameworks used in academic research and professional settings worldwide. While no online assessment can replace a clinical evaluation, our tools provide meaningful insights grounded in established personality science."
  },
  {
    question: "Is it safe for kids?",
    answer: "Absolutely. Our age-tiered system ensures that younger users (ages 7-12) receive age-appropriate questions and explanations. We don't collect personal information from minors, and all content is designed to be educational and empowering."
  },
  {
    question: "What personality frameworks do you use?",
    answer: "We use three complementary frameworks: the Big Five (OCEAN) model — the gold standard in academic personality research; MBTI-inspired typing for understanding cognitive preferences; and DISC for behavioral and workplace insights. Together, they give you a well-rounded view of your personality."
  },
  {
    question: "Can I retake the assessment?",
    answer: "Yes, you can retake the assessment anytime. Personality can shift based on mood, life stage, and personal growth, so retaking it periodically can reveal how you're evolving."
  },
  {
    question: "Do I need to create an account?",
    answer: "No account is needed to take the assessment and view your basic results. Creating a free account lets you save your results, access premium insights, and track changes over time."
  },
  {
    question: "How is my data handled?",
    answer: "We take privacy seriously. Your assessment responses are processed to generate results and are not shared with third parties. See our Privacy Policy for full details on how we handle your information."
  },
  {
    question: "What are the career matches based on?",
    answer: "Career matches are generated by mapping your personality traits across all three frameworks to career profiles based on research into which personality types tend to thrive in specific roles. We match you with 150+ career paths."
  }
];

function FaqItem({ question, answer }: { question: string; answer: string }) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="border-b border-warm-gray/10 dark:border-[#A78BFA]/10">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-center justify-between py-4 text-left"
        data-testid={`button-faq-${question.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 30)}`}
      >
        <span className="font-medium text-warm-gray dark:text-[#F8FAFC] pr-4">{question}</span>
        <ChevronDown className={`w-5 h-5 text-warm-gray/50 dark:text-[#94A3B8] flex-shrink-0 transition-transform ${isOpen ? "rotate-180" : ""}`} />
      </button>
      {isOpen && (
        <p className="pb-4 text-sm text-warm-gray/70 dark:text-[#94A3B8] leading-relaxed">
          {answer}
        </p>
      )}
    </div>
  );
}

export default function Faq() {
  return (
    <div className="min-h-screen bg-soft-cream dark:bg-[#0A0A12] text-warm-gray dark:text-[#F8FAFC]">
      <header className="sticky top-0 z-50 px-6 py-4 bg-soft-cream/90 dark:bg-[#0A0A12]/90 backdrop-blur-sm border-b border-warm-gray/10 dark:border-[#A78BFA]/10">
        <div className="max-w-2xl mx-auto flex items-center gap-3">
          <Link href="/" className="flex items-center gap-2 text-sm text-warm-gray/70 dark:text-[#94A3B8] hover:text-terracotta dark:hover:text-[#A78BFA] transition-colors" data-testid="link-back-home">
              <ArrowLeft className="w-4 h-4" />
              Back to Home
          </Link>
        </div>
      </header>

      <main className="max-w-2xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-display font-bold mb-2" data-testid="text-faq-title">Frequently Asked Questions</h1>
        <p className="text-warm-gray/60 dark:text-[#94A3B8] mb-8">Everything you need to know about KnowYouRole</p>

        <div className="space-y-0">
          {FAQ_ITEMS.map((item) => (
            <FaqItem key={item.question} question={item.question} answer={item.answer} />
          ))}
        </div>
      </main>
    </div>
  );
}
