import { db } from "./db";
import { jobRoles, type InsertJobRole } from "@shared/schema";

const JOB_ROLES_DATA: InsertJobRole[] = [
  { roleNumber: 1, roleName: "Software Developer", mbtiEI: 2, mbtiSN: 2, mbtiTF: 4, mbtiJP: 3, discD: 3, discI: 2, discS: 2, discC: 5, big5O: 4, big5C: 5, big5E: 2, big5A: 3, big5N: 2, jobCollar: "white" },
  { roleNumber: 2, roleName: "Nurse Practitioner", mbtiEI: 4, mbtiSN: 4, mbtiTF: 3, mbtiJP: 4, discD: 4, discI: 4, discS: 5, discC: 4, big5O: 3, big5C: 5, big5E: 4, big5A: 5, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 3, roleName: "Physician Assistant", mbtiEI: 4, mbtiSN: 4, mbtiTF: 4, mbtiJP: 4, discD: 4, discI: 4, discS: 4, discC: 5, big5O: 3, big5C: 5, big5E: 4, big5A: 5, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 4, roleName: "Data Scientist", mbtiEI: 2, mbtiSN: 2, mbtiTF: 5, mbtiJP: 3, discD: 3, discI: 2, discS: 2, discC: 5, big5O: 5, big5C: 5, big5E: 2, big5A: 3, big5N: 2, jobCollar: "white" },
  { roleNumber: 5, roleName: "Financial Manager", mbtiEI: 4, mbtiSN: 3, mbtiTF: 5, mbtiJP: 5, discD: 5, discI: 3, discS: 3, discC: 4, big5O: 3, big5C: 5, big5E: 4, big5A: 3, big5N: 3, jobCollar: "white" },
  { roleNumber: 6, roleName: "Registered Nurse", mbtiEI: 4, mbtiSN: 4, mbtiTF: 3, mbtiJP: 4, discD: 3, discI: 4, discS: 5, discC: 4, big5O: 3, big5C: 5, big5E: 4, big5A: 5, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 7, roleName: "Dentist", mbtiEI: 3, mbtiSN: 4, mbtiTF: 4, mbtiJP: 5, discD: 4, discI: 3, discS: 4, discC: 5, big5O: 3, big5C: 5, big5E: 3, big5A: 4, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 8, roleName: "Lawyer", mbtiEI: 4, mbtiSN: 2, mbtiTF: 5, mbtiJP: 5, discD: 5, discI: 4, discS: 2, discC: 4, big5O: 4, big5C: 4, big5E: 5, big5A: 3, big5N: 4, jobCollar: "white" },
  { roleNumber: 9, roleName: "Marketing Manager", mbtiEI: 5, mbtiSN: 2, mbtiTF: 4, mbtiJP: 4, discD: 5, discI: 5, discS: 3, discC: 3, big5O: 5, big5C: 4, big5E: 5, big5A: 4, big5N: 3, jobCollar: "white" },
  { roleNumber: 10, roleName: "IT Manager", mbtiEI: 4, mbtiSN: 3, mbtiTF: 5, mbtiJP: 5, discD: 5, discI: 3, discS: 3, discC: 4, big5O: 3, big5C: 5, big5E: 4, big5A: 3, big5N: 3, jobCollar: "white" },
  { roleNumber: 11, roleName: "Accountant", mbtiEI: 2, mbtiSN: 3, mbtiTF: 5, mbtiJP: 5, discD: 2, discI: 2, discS: 3, discC: 5, big5O: 2, big5C: 5, big5E: 2, big5A: 3, big5N: 2, jobCollar: "white" },
  { roleNumber: 12, roleName: "Human Resources Manager", mbtiEI: 5, mbtiSN: 3, mbtiTF: 3, mbtiJP: 4, discD: 4, discI: 5, discS: 4, discC: 3, big5O: 3, big5C: 4, big5E: 5, big5A: 5, big5N: 3, jobCollar: "white" },
  { roleNumber: 13, roleName: "Teacher (High School)", mbtiEI: 5, mbtiSN: 3, mbtiTF: 3, mbtiJP: 4, discD: 3, discI: 5, discS: 4, discC: 3, big5O: 4, big5C: 4, big5E: 5, big5A: 5, big5N: 3, jobCollar: "white" },
  { roleNumber: 14, roleName: "Electrician", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 4, discD: 3, discI: 2, discS: 4, discC: 4, big5O: 2, big5C: 5, big5E: 3, big5A: 3, big5N: 2, jobCollar: "blue" },
  { roleNumber: 15, roleName: "Plumber", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 3, discI: 2, discS: 4, discC: 4, big5O: 2, big5C: 5, big5E: 3, big5A: 3, big5N: 2, jobCollar: "blue" },
  { roleNumber: 16, roleName: "Carpenter", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 3, discI: 2, discS: 4, discC: 4, big5O: 3, big5C: 5, big5E: 3, big5A: 3, big5N: 2, jobCollar: "blue" },
  { roleNumber: 17, roleName: "Truck Driver", mbtiEI: 2, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 3, discI: 2, discS: 5, discC: 3, big5O: 2, big5C: 5, big5E: 2, big5A: 3, big5N: 2, jobCollar: "blue" },
  { roleNumber: 18, roleName: "Construction Manager", mbtiEI: 4, mbtiSN: 4, mbtiTF: 5, mbtiJP: 5, discD: 5, discI: 3, discS: 3, discC: 4, big5O: 3, big5C: 5, big5E: 4, big5A: 3, big5N: 3, jobCollar: "blue" },
  { roleNumber: 19, roleName: "Mechanic (Automotive)", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 3, discI: 2, discS: 4, discC: 4, big5O: 2, big5C: 5, big5E: 3, big5A: 3, big5N: 2, jobCollar: "blue" },
  { roleNumber: 20, roleName: "Welder", mbtiEI: 2, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 3, discI: 2, discS: 4, discC: 4, big5O: 3, big5C: 5, big5E: 2, big5A: 3, big5N: 2, jobCollar: "blue" },
  { roleNumber: 21, roleName: "Retail Salesperson", mbtiEI: 5, mbtiSN: 4, mbtiTF: 3, mbtiJP: 3, discD: 3, discI: 5, discS: 4, discC: 3, big5O: 3, big5C: 4, big5E: 5, big5A: 4, big5N: 3, jobCollar: "service" },
  { roleNumber: 22, roleName: "Customer Service Representative", mbtiEI: 5, mbtiSN: 4, mbtiTF: 3, mbtiJP: 4, discD: 3, discI: 5, discS: 5, discC: 3, big5O: 3, big5C: 4, big5E: 5, big5A: 5, big5N: 3, jobCollar: "service" },
  { roleNumber: 23, roleName: "Fast Food Worker", mbtiEI: 4, mbtiSN: 5, mbtiTF: 3, mbtiJP: 3, discD: 2, discI: 4, discS: 5, discC: 3, big5O: 2, big5C: 4, big5E: 4, big5A: 4, big5N: 3, jobCollar: "service" },
  { roleNumber: 24, roleName: "Home Health Aide", mbtiEI: 4, mbtiSN: 5, mbtiTF: 2, mbtiJP: 4, discD: 2, discI: 4, discS: 5, discC: 3, big5O: 2, big5C: 4, big5E: 4, big5A: 5, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 25, roleName: "Janitor/Cleaner", mbtiEI: 2, mbtiSN: 5, mbtiTF: 3, mbtiJP: 3, discD: 2, discI: 2, discS: 5, discC: 3, big5O: 1, big5C: 4, big5E: 2, big5A: 4, big5N: 2, jobCollar: "service" },
  { roleNumber: 26, roleName: "Graphic Designer", mbtiEI: 3, mbtiSN: 2, mbtiTF: 3, mbtiJP: 2, discD: 3, discI: 4, discS: 2, discC: 4, big5O: 5, big5C: 4, big5E: 3, big5A: 4, big5N: 2, jobCollar: "arts" },
  { roleNumber: 27, roleName: "Writer/Author", mbtiEI: 2, mbtiSN: 2, mbtiTF: 3, mbtiJP: 2, discD: 3, discI: 3, discS: 2, discC: 4, big5O: 5, big5C: 4, big5E: 2, big5A: 3, big5N: 2, jobCollar: "arts" },
  { roleNumber: 28, roleName: "Actor", mbtiEI: 5, mbtiSN: 2, mbtiTF: 2, mbtiJP: 2, discD: 4, discI: 5, discS: 2, discC: 2, big5O: 5, big5C: 3, big5E: 5, big5A: 4, big5N: 4, jobCollar: "arts" },
  { roleNumber: 29, roleName: "Musician", mbtiEI: 4, mbtiSN: 2, mbtiTF: 2, mbtiJP: 2, discD: 4, discI: 5, discS: 2, discC: 3, big5O: 5, big5C: 4, big5E: 4, big5A: 4, big5N: 3, jobCollar: "arts" },
  { roleNumber: 30, roleName: "Photographer", mbtiEI: 3, mbtiSN: 3, mbtiTF: 3, mbtiJP: 2, discD: 3, discI: 4, discS: 2, discC: 3, big5O: 5, big5C: 4, big5E: 3, big5A: 4, big5N: 3, jobCollar: "arts" },
  { roleNumber: 31, roleName: "Chef", mbtiEI: 4, mbtiSN: 4, mbtiTF: 3, mbtiJP: 3, discD: 4, discI: 4, discS: 3, discC: 4, big5O: 4, big5C: 4, big5E: 4, big5A: 3, big5N: 3, jobCollar: "service" },
  { roleNumber: 32, roleName: "Police Officer", mbtiEI: 4, mbtiSN: 4, mbtiTF: 4, mbtiJP: 5, discD: 5, discI: 3, discS: 4, discC: 4, big5O: 3, big5C: 5, big5E: 4, big5A: 4, big5N: 4, jobCollar: "service" },
  { roleNumber: 33, roleName: "Firefighter", mbtiEI: 4, mbtiSN: 5, mbtiTF: 4, mbtiJP: 4, discD: 5, discI: 3, discS: 4, discC: 3, big5O: 3, big5C: 5, big5E: 4, big5A: 4, big5N: 4, jobCollar: "service" },
  { roleNumber: 34, roleName: "Paramedic/EMT", mbtiEI: 4, mbtiSN: 5, mbtiTF: 4, mbtiJP: 4, discD: 4, discI: 3, discS: 5, discC: 4, big5O: 3, big5C: 5, big5E: 4, big5A: 5, big5N: 4, jobCollar: "healthcare" },
  { roleNumber: 35, roleName: "Physical Therapist", mbtiEI: 4, mbtiSN: 4, mbtiTF: 3, mbtiJP: 4, discD: 4, discI: 4, discS: 4, discC: 4, big5O: 3, big5C: 5, big5E: 4, big5A: 5, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 36, roleName: "Occupational Therapist", mbtiEI: 4, mbtiSN: 3, mbtiTF: 3, mbtiJP: 4, discD: 4, discI: 4, discS: 4, discC: 4, big5O: 4, big5C: 5, big5E: 4, big5A: 5, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 37, roleName: "Speech-Language Pathologist", mbtiEI: 4, mbtiSN: 3, mbtiTF: 3, mbtiJP: 4, discD: 3, discI: 4, discS: 4, discC: 4, big5O: 4, big5C: 5, big5E: 4, big5A: 5, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 38, roleName: "Psychologist", mbtiEI: 3, mbtiSN: 2, mbtiTF: 2, mbtiJP: 4, discD: 3, discI: 4, discS: 4, discC: 4, big5O: 4, big5C: 4, big5E: 3, big5A: 5, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 39, roleName: "Social Worker", mbtiEI: 5, mbtiSN: 3, mbtiTF: 2, mbtiJP: 4, discD: 3, discI: 5, discS: 5, discC: 3, big5O: 4, big5C: 4, big5E: 5, big5A: 5, big5N: 3, jobCollar: "service" },
  { roleNumber: 40, roleName: "Counselor", mbtiEI: 4, mbtiSN: 2, mbtiTF: 2, mbtiJP: 4, discD: 3, discI: 5, discS: 5, discC: 3, big5O: 4, big5C: 4, big5E: 4, big5A: 5, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 41, roleName: "Sales Manager", mbtiEI: 5, mbtiSN: 3, mbtiTF: 4, mbtiJP: 4, discD: 5, discI: 5, discS: 3, discC: 3, big5O: 4, big5C: 4, big5E: 5, big5A: 4, big5N: 3, jobCollar: "white" },
  { roleNumber: 42, roleName: "Real Estate Agent", mbtiEI: 5, mbtiSN: 3, mbtiTF: 3, mbtiJP: 3, discD: 4, discI: 5, discS: 3, discC: 3, big5O: 4, big5C: 4, big5E: 5, big5A: 4, big5N: 3, jobCollar: "service" },
  { roleNumber: 43, roleName: "Insurance Agent", mbtiEI: 5, mbtiSN: 3, mbtiTF: 4, mbtiJP: 4, discD: 4, discI: 5, discS: 3, discC: 4, big5O: 3, big5C: 4, big5E: 5, big5A: 4, big5N: 3, jobCollar: "service" },
  { roleNumber: 44, roleName: "Financial Advisor", mbtiEI: 4, mbtiSN: 2, mbtiTF: 4, mbtiJP: 5, discD: 4, discI: 4, discS: 3, discC: 4, big5O: 3, big5C: 5, big5E: 4, big5A: 4, big5N: 3, jobCollar: "white" },
  { roleNumber: 45, roleName: "Project Manager", mbtiEI: 4, mbtiSN: 3, mbtiTF: 5, mbtiJP: 5, discD: 5, discI: 4, discS: 3, discC: 4, big5O: 3, big5C: 5, big5E: 4, big5A: 3, big5N: 3, jobCollar: "white" },
  { roleNumber: 46, roleName: "Business Analyst", mbtiEI: 3, mbtiSN: 2, mbtiTF: 5, mbtiJP: 4, discD: 4, discI: 3, discS: 3, discC: 5, big5O: 4, big5C: 5, big5E: 3, big5A: 3, big5N: 2, jobCollar: "white" },
  { roleNumber: 47, roleName: "Web Developer", mbtiEI: 2, mbtiSN: 2, mbtiTF: 4, mbtiJP: 3, discD: 3, discI: 2, discS: 2, discC: 5, big5O: 4, big5C: 5, big5E: 2, big5A: 3, big5N: 2, jobCollar: "white" },
  { roleNumber: 48, roleName: "Cybersecurity Analyst", mbtiEI: 2, mbtiSN: 2, mbtiTF: 5, mbtiJP: 4, discD: 4, discI: 2, discS: 2, discC: 5, big5O: 4, big5C: 5, big5E: 2, big5A: 3, big5N: 2, jobCollar: "white" },
  { roleNumber: 49, roleName: "Nurse Anesthetist", mbtiEI: 3, mbtiSN: 4, mbtiTF: 4, mbtiJP: 5, discD: 4, discI: 3, discS: 4, discC: 5, big5O: 3, big5C: 5, big5E: 3, big5A: 4, big5N: 4, jobCollar: "healthcare" },
  { roleNumber: 50, roleName: "Physician", mbtiEI: 3, mbtiSN: 3, mbtiTF: 4, mbtiJP: 5, discD: 5, discI: 3, discS: 3, discC: 5, big5O: 4, big5C: 5, big5E: 3, big5A: 4, big5N: 4, jobCollar: "healthcare" },
  { roleNumber: 51, roleName: "Pharmacist", mbtiEI: 3, mbtiSN: 4, mbtiTF: 4, mbtiJP: 5, discD: 3, discI: 3, discS: 4, discC: 5, big5O: 3, big5C: 5, big5E: 3, big5A: 4, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 52, roleName: "Veterinarian", mbtiEI: 3, mbtiSN: 4, mbtiTF: 4, mbtiJP: 4, discD: 4, discI: 3, discS: 4, discC: 4, big5O: 3, big5C: 5, big5E: 3, big5A: 5, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 53, roleName: "Architect", mbtiEI: 3, mbtiSN: 2, mbtiTF: 4, mbtiJP: 4, discD: 4, discI: 3, discS: 3, discC: 4, big5O: 5, big5C: 5, big5E: 3, big5A: 3, big5N: 3, jobCollar: "white" },
  { roleNumber: 54, roleName: "Civil Engineer", mbtiEI: 3, mbtiSN: 3, mbtiTF: 5, mbtiJP: 5, discD: 4, discI: 2, discS: 3, discC: 5, big5O: 3, big5C: 5, big5E: 3, big5A: 3, big5N: 2, jobCollar: "white" },
  { roleNumber: 55, roleName: "Mechanical Engineer", mbtiEI: 2, mbtiSN: 3, mbtiTF: 5, mbtiJP: 4, discD: 4, discI: 2, discS: 3, discC: 5, big5O: 4, big5C: 5, big5E: 2, big5A: 3, big5N: 2, jobCollar: "white" },
  { roleNumber: 56, roleName: "Electrical Engineer", mbtiEI: 2, mbtiSN: 3, mbtiTF: 5, mbtiJP: 4, discD: 4, discI: 2, discS: 3, discC: 5, big5O: 4, big5C: 5, big5E: 2, big5A: 3, big5N: 2, jobCollar: "white" },
  { roleNumber: 57, roleName: "HVAC Technician", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 3, discI: 2, discS: 4, discC: 4, big5O: 2, big5C: 5, big5E: 3, big5A: 3, big5N: 2, jobCollar: "blue" },
  { roleNumber: 58, roleName: "Landscaper/Groundskeeper", mbtiEI: 3, mbtiSN: 5, mbtiTF: 3, mbtiJP: 3, discD: 2, discI: 3, discS: 5, discC: 3, big5O: 2, big5C: 4, big5E: 3, big5A: 4, big5N: 2, jobCollar: "blue" },
  { roleNumber: 59, roleName: "Painter (Construction)", mbtiEI: 2, mbtiSN: 5, mbtiTF: 3, mbtiJP: 3, discD: 2, discI: 2, discS: 4, discC: 3, big5O: 3, big5C: 4, big5E: 2, big5A: 3, big5N: 2, jobCollar: "blue" },
  { roleNumber: 60, roleName: "Roofer", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 3, discI: 2, discS: 4, discC: 3, big5O: 2, big5C: 4, big5E: 3, big5A: 3, big5N: 3, jobCollar: "blue" },
  { roleNumber: 61, roleName: "Mason (Brick/Stone)", mbtiEI: 2, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 3, discI: 2, discS: 4, discC: 4, big5O: 3, big5C: 5, big5E: 2, big5A: 3, big5N: 2, jobCollar: "blue" },
  { roleNumber: 62, roleName: "Delivery Driver", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 3, discI: 3, discS: 5, discC: 3, big5O: 2, big5C: 4, big5E: 3, big5A: 4, big5N: 2, jobCollar: "blue" },
  { roleNumber: 63, roleName: "Warehouse Worker", mbtiEI: 3, mbtiSN: 5, mbtiTF: 3, mbtiJP: 3, discD: 2, discI: 3, discS: 5, discC: 3, big5O: 2, big5C: 4, big5E: 3, big5A: 4, big5N: 2, jobCollar: "blue" },
  { roleNumber: 64, roleName: "Factory Assembler", mbtiEI: 2, mbtiSN: 5, mbtiTF: 4, mbtiJP: 4, discD: 2, discI: 2, discS: 5, discC: 4, big5O: 2, big5C: 5, big5E: 2, big5A: 3, big5N: 2, jobCollar: "blue" },
  { roleNumber: 65, roleName: "Machinist", mbtiEI: 2, mbtiSN: 5, mbtiTF: 4, mbtiJP: 4, discD: 3, discI: 2, discS: 4, discC: 5, big5O: 3, big5C: 5, big5E: 2, big5A: 3, big5N: 2, jobCollar: "blue" },
  { roleNumber: 66, roleName: "Farmer/Rancher", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 4, discI: 2, discS: 4, discC: 3, big5O: 3, big5C: 5, big5E: 3, big5A: 3, big5N: 3, jobCollar: "blue" },
  { roleNumber: 67, roleName: "Fisherman", mbtiEI: 2, mbtiSN: 5, mbtiTF: 4, mbtiJP: 2, discD: 4, discI: 2, discS: 4, discC: 3, big5O: 3, big5C: 4, big5E: 2, big5A: 3, big5N: 4, jobCollar: "blue" },
  { roleNumber: 68, roleName: "Logger", mbtiEI: 2, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 4, discI: 2, discS: 4, discC: 3, big5O: 2, big5C: 4, big5E: 2, big5A: 3, big5N: 4, jobCollar: "blue" },
  { roleNumber: 69, roleName: "Flight Attendant", mbtiEI: 5, mbtiSN: 4, mbtiTF: 3, mbtiJP: 4, discD: 3, discI: 5, discS: 5, discC: 3, big5O: 3, big5C: 4, big5E: 5, big5A: 5, big5N: 3, jobCollar: "service" },
  { roleNumber: 70, roleName: "Pilot", mbtiEI: 3, mbtiSN: 4, mbtiTF: 5, mbtiJP: 5, discD: 5, discI: 3, discS: 3, discC: 5, big5O: 3, big5C: 5, big5E: 3, big5A: 3, big5N: 4, jobCollar: "white" },
  { roleNumber: 71, roleName: "Barista", mbtiEI: 4, mbtiSN: 5, mbtiTF: 3, mbtiJP: 3, discD: 2, discI: 4, discS: 5, discC: 3, big5O: 2, big5C: 4, big5E: 4, big5A: 5, big5N: 3, jobCollar: "service" },
  { roleNumber: 72, roleName: "Bartender", mbtiEI: 5, mbtiSN: 4, mbtiTF: 3, mbtiJP: 2, discD: 3, discI: 5, discS: 4, discC: 3, big5O: 3, big5C: 4, big5E: 5, big5A: 4, big5N: 3, jobCollar: "service" },
  { roleNumber: 73, roleName: "Server (Restaurant)", mbtiEI: 5, mbtiSN: 4, mbtiTF: 3, mbtiJP: 3, discD: 3, discI: 5, discS: 5, discC: 3, big5O: 3, big5C: 4, big5E: 5, big5A: 5, big5N: 3, jobCollar: "service" },
  { roleNumber: 74, roleName: "Hair Stylist", mbtiEI: 5, mbtiSN: 4, mbtiTF: 2, mbtiJP: 2, discD: 3, discI: 5, discS: 4, discC: 3, big5O: 4, big5C: 4, big5E: 5, big5A: 5, big5N: 3, jobCollar: "service" },
  { roleNumber: 75, roleName: "Fitness Trainer", mbtiEI: 5, mbtiSN: 4, mbtiTF: 3, mbtiJP: 3, discD: 4, discI: 5, discS: 4, discC: 3, big5O: 4, big5C: 4, big5E: 5, big5A: 5, big5N: 3, jobCollar: "service" },
  { roleNumber: 76, roleName: "Freelance Writer (side hustle)", mbtiEI: 2, mbtiSN: 2, mbtiTF: 3, mbtiJP: 2, discD: 3, discI: 3, discS: 2, discC: 4, big5O: 5, big5C: 4, big5E: 2, big5A: 3, big5N: 2, jobCollar: "arts" },
  { roleNumber: 77, roleName: "Uber/Lyft Driver (side hustle)", mbtiEI: 4, mbtiSN: 5, mbtiTF: 3, mbtiJP: 2, discD: 3, discI: 4, discS: 4, discC: 3, big5O: 3, big5C: 4, big5E: 4, big5A: 4, big5N: 3, jobCollar: "service" },
  { roleNumber: 78, roleName: "Content Creator/YouTuber", mbtiEI: 5, mbtiSN: 2, mbtiTF: 3, mbtiJP: 2, discD: 4, discI: 5, discS: 2, discC: 3, big5O: 5, big5C: 4, big5E: 5, big5A: 4, big5N: 3, jobCollar: "arts" },
  { roleNumber: 79, roleName: "Etsy Seller/Handcrafter (side hustle)", mbtiEI: 3, mbtiSN: 3, mbtiTF: 3, mbtiJP: 2, discD: 3, discI: 4, discS: 3, discC: 4, big5O: 5, big5C: 4, big5E: 3, big5A: 4, big5N: 2, jobCollar: "arts" },
  { roleNumber: 80, roleName: "Tutor (online/in-person)", mbtiEI: 4, mbtiSN: 3, mbtiTF: 3, mbtiJP: 4, discD: 3, discI: 5, discS: 4, discC: 4, big5O: 4, big5C: 4, big5E: 4, big5A: 5, big5N: 3, jobCollar: "service" },
  { roleNumber: 81, roleName: "Event Planner", mbtiEI: 5, mbtiSN: 3, mbtiTF: 3, mbtiJP: 4, discD: 4, discI: 5, discS: 4, discC: 4, big5O: 4, big5C: 5, big5E: 5, big5A: 5, big5N: 3, jobCollar: "service" },
  { roleNumber: 82, roleName: "Interior Designer", mbtiEI: 4, mbtiSN: 2, mbtiTF: 3, mbtiJP: 3, discD: 4, discI: 4, discS: 3, discC: 4, big5O: 5, big5C: 4, big5E: 4, big5A: 4, big5N: 3, jobCollar: "arts" },
  { roleNumber: 83, roleName: "Film Director", mbtiEI: 5, mbtiSN: 2, mbtiTF: 3, mbtiJP: 3, discD: 5, discI: 5, discS: 2, discC: 3, big5O: 5, big5C: 4, big5E: 5, big5A: 4, big5N: 4, jobCollar: "arts" },
  { roleNumber: 84, roleName: "Animator", mbtiEI: 2, mbtiSN: 2, mbtiTF: 3, mbtiJP: 2, discD: 3, discI: 3, discS: 2, discC: 4, big5O: 5, big5C: 5, big5E: 2, big5A: 3, big5N: 2, jobCollar: "arts" },
  { roleNumber: 85, roleName: "Journalist", mbtiEI: 4, mbtiSN: 2, mbtiTF: 4, mbtiJP: 3, discD: 4, discI: 4, discS: 2, discC: 4, big5O: 5, big5C: 4, big5E: 4, big5A: 3, big5N: 3, jobCollar: "white" },
  { roleNumber: 86, roleName: "Public Relations Specialist", mbtiEI: 5, mbtiSN: 2, mbtiTF: 3, mbtiJP: 4, discD: 4, discI: 5, discS: 3, discC: 3, big5O: 4, big5C: 4, big5E: 5, big5A: 5, big5N: 3, jobCollar: "white" },
  { roleNumber: 87, roleName: "Librarian", mbtiEI: 3, mbtiSN: 3, mbtiTF: 3, mbtiJP: 5, discD: 2, discI: 4, discS: 5, discC: 4, big5O: 4, big5C: 5, big5E: 3, big5A: 5, big5N: 2, jobCollar: "service" },
  { roleNumber: 88, roleName: "Museum Curator", mbtiEI: 3, mbtiSN: 2, mbtiTF: 3, mbtiJP: 5, discD: 3, discI: 4, discS: 4, discC: 4, big5O: 5, big5C: 5, big5E: 3, big5A: 4, big5N: 2, jobCollar: "arts" },
  { roleNumber: 89, roleName: "Park Ranger", mbtiEI: 4, mbtiSN: 4, mbtiTF: 4, mbtiJP: 4, discD: 4, discI: 4, discS: 4, discC: 4, big5O: 4, big5C: 5, big5E: 4, big5A: 4, big5N: 3, jobCollar: "service" },
  { roleNumber: 90, roleName: "Environmental Scientist", mbtiEI: 3, mbtiSN: 3, mbtiTF: 5, mbtiJP: 4, discD: 4, discI: 3, discS: 3, discC: 5, big5O: 4, big5C: 5, big5E: 3, big5A: 4, big5N: 3, jobCollar: "white" },
  { roleNumber: 91, roleName: "Data Entry Clerk", mbtiEI: 2, mbtiSN: 4, mbtiTF: 4, mbtiJP: 5, discD: 2, discI: 2, discS: 5, discC: 5, big5O: 1, big5C: 5, big5E: 2, big5A: 3, big5N: 1, jobCollar: "white" },
  { roleNumber: 92, roleName: "Administrative Assistant", mbtiEI: 4, mbtiSN: 4, mbtiTF: 3, mbtiJP: 5, discD: 3, discI: 4, discS: 5, discC: 4, big5O: 2, big5C: 5, big5E: 4, big5A: 5, big5N: 2, jobCollar: "white" },
  { roleNumber: 93, roleName: "Executive Assistant", mbtiEI: 4, mbtiSN: 3, mbtiTF: 3, mbtiJP: 5, discD: 3, discI: 4, discS: 5, discC: 4, big5O: 3, big5C: 5, big5E: 4, big5A: 5, big5N: 2, jobCollar: "white" },
  { roleNumber: 94, roleName: "Operations Manager", mbtiEI: 4, mbtiSN: 4, mbtiTF: 5, mbtiJP: 5, discD: 5, discI: 3, discS: 4, discC: 4, big5O: 3, big5C: 5, big5E: 4, big5A: 3, big5N: 3, jobCollar: "white" },
  { roleNumber: 95, roleName: "Logistics Coordinator", mbtiEI: 3, mbtiSN: 4, mbtiTF: 4, mbtiJP: 5, discD: 4, discI: 3, discS: 4, discC: 4, big5O: 3, big5C: 5, big5E: 3, big5A: 3, big5N: 2, jobCollar: "white" },
  { roleNumber: 96, roleName: "Supply Chain Analyst", mbtiEI: 3, mbtiSN: 3, mbtiTF: 5, mbtiJP: 4, discD: 4, discI: 3, discS: 3, discC: 5, big5O: 3, big5C: 5, big5E: 3, big5A: 3, big5N: 2, jobCollar: "white" },
  { roleNumber: 97, roleName: "Dental Hygienist", mbtiEI: 4, mbtiSN: 5, mbtiTF: 3, mbtiJP: 4, discD: 3, discI: 4, discS: 5, discC: 4, big5O: 2, big5C: 5, big5E: 4, big5A: 5, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 98, roleName: "Radiologic Technologist", mbtiEI: 3, mbtiSN: 4, mbtiTF: 4, mbtiJP: 4, discD: 3, discI: 3, discS: 4, discC: 5, big5O: 3, big5C: 5, big5E: 3, big5A: 4, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 99, roleName: "Wind Turbine Technician", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 4, discI: 2, discS: 4, discC: 4, big5O: 3, big5C: 5, big5E: 3, big5A: 3, big5N: 3, jobCollar: "blue" },
  { roleNumber: 100, roleName: "Solar Photovoltaic Installer", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 4, discD: 3, discI: 2, discS: 4, discC: 4, big5O: 2, big5C: 5, big5E: 3, big5A: 3, big5N: 2, jobCollar: "blue" },
  { roleNumber: 101, roleName: "Cashier", mbtiEI: 4, mbtiSN: 5, mbtiTF: 3, mbtiJP: 3, discD: 2, discI: 4, discS: 5, discC: 3, big5O: 2, big5C: 4, big5E: 4, big5A: 4, big5N: 2, jobCollar: "service" },
  { roleNumber: 102, roleName: "Stock Clerk/Order Filler", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 4, discD: 2, discI: 3, discS: 5, discC: 4, big5O: 2, big5C: 5, big5E: 3, big5A: 3, big5N: 2, jobCollar: "service" },
  { roleNumber: 103, roleName: "General Office Clerk", mbtiEI: 3, mbtiSN: 4, mbtiTF: 3, mbtiJP: 5, discD: 2, discI: 3, discS: 5, discC: 4, big5O: 2, big5C: 5, big5E: 3, big5A: 4, big5N: 2, jobCollar: "white" },
  { roleNumber: 104, roleName: "Bookkeeping Clerk", mbtiEI: 2, mbtiSN: 4, mbtiTF: 4, mbtiJP: 5, discD: 2, discI: 2, discS: 4, discC: 5, big5O: 2, big5C: 5, big5E: 2, big5A: 3, big5N: 1, jobCollar: "white" },
  { roleNumber: 105, roleName: "Laborer (Construction)", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 2, discI: 3, discS: 5, discC: 3, big5O: 2, big5C: 4, big5E: 3, big5A: 4, big5N: 2, jobCollar: "blue" },
  { roleNumber: 106, roleName: "Heavy Equipment Operator", mbtiEI: 2, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 3, discI: 2, discS: 4, discC: 3, big5O: 2, big5C: 5, big5E: 2, big5A: 3, big5N: 3, jobCollar: "blue" },
  { roleNumber: 107, roleName: "Bus Driver", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 4, discD: 3, discI: 3, discS: 5, discC: 3, big5O: 2, big5C: 5, big5E: 3, big5A: 4, big5N: 3, jobCollar: "service" },
  { roleNumber: 108, roleName: "Security Guard", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 4, discD: 4, discI: 3, discS: 5, discC: 4, big5O: 2, big5C: 5, big5E: 3, big5A: 4, big5N: 3, jobCollar: "service" },
  { roleNumber: 109, roleName: "Correctional Officer", mbtiEI: 4, mbtiSN: 4, mbtiTF: 4, mbtiJP: 5, discD: 5, discI: 3, discS: 4, discC: 4, big5O: 2, big5C: 5, big5E: 4, big5A: 3, big5N: 4, jobCollar: "service" },
  { roleNumber: 110, roleName: "Preschool Teacher", mbtiEI: 5, mbtiSN: 4, mbtiTF: 2, mbtiJP: 4, discD: 3, discI: 5, discS: 5, discC: 3, big5O: 4, big5C: 4, big5E: 5, big5A: 5, big5N: 3, jobCollar: "service" },
  { roleNumber: 111, roleName: "Elementary School Teacher", mbtiEI: 5, mbtiSN: 3, mbtiTF: 2, mbtiJP: 4, discD: 3, discI: 5, discS: 5, discC: 3, big5O: 4, big5C: 5, big5E: 5, big5A: 5, big5N: 3, jobCollar: "white" },
  { roleNumber: 112, roleName: "Postsecondary Teacher", mbtiEI: 4, mbtiSN: 2, mbtiTF: 3, mbtiJP: 4, discD: 4, discI: 5, discS: 3, discC: 4, big5O: 5, big5C: 4, big5E: 4, big5A: 4, big5N: 3, jobCollar: "white" },
  { roleNumber: 113, roleName: "Medical Assistant", mbtiEI: 4, mbtiSN: 5, mbtiTF: 3, mbtiJP: 4, discD: 3, discI: 4, discS: 5, discC: 4, big5O: 2, big5C: 5, big5E: 4, big5A: 5, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 114, roleName: "Pharmacy Technician", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 5, discD: 2, discI: 3, discS: 5, discC: 5, big5O: 2, big5C: 5, big5E: 3, big5A: 4, big5N: 2, jobCollar: "healthcare" },
  { roleNumber: 115, roleName: "Licensed Practical Nurse", mbtiEI: 4, mbtiSN: 5, mbtiTF: 3, mbtiJP: 4, discD: 3, discI: 4, discS: 5, discC: 4, big5O: 3, big5C: 5, big5E: 4, big5A: 5, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 116, roleName: "Clinical Lab Technician", mbtiEI: 2, mbtiSN: 4, mbtiTF: 4, mbtiJP: 5, discD: 2, discI: 2, discS: 4, discC: 5, big5O: 3, big5C: 5, big5E: 2, big5A: 3, big5N: 2, jobCollar: "healthcare" },
  { roleNumber: 117, roleName: "Dancer", mbtiEI: 5, mbtiSN: 3, mbtiTF: 2, mbtiJP: 2, discD: 4, discI: 5, discS: 2, discC: 2, big5O: 5, big5C: 4, big5E: 5, big5A: 4, big5N: 4, jobCollar: "arts" },
  { roleNumber: 118, roleName: "Choreographer", mbtiEI: 5, mbtiSN: 2, mbtiTF: 2, mbtiJP: 3, discD: 5, discI: 5, discS: 2, discC: 3, big5O: 5, big5C: 4, big5E: 5, big5A: 4, big5N: 3, jobCollar: "arts" },
  { roleNumber: 119, roleName: "Fine Artist (Painter/Sculptor)", mbtiEI: 2, mbtiSN: 2, mbtiTF: 2, mbtiJP: 1, discD: 3, discI: 3, discS: 2, discC: 3, big5O: 5, big5C: 4, big5E: 2, big5A: 3, big5N: 2, jobCollar: "arts" },
  { roleNumber: 120, roleName: "Fashion Designer", mbtiEI: 4, mbtiSN: 2, mbtiTF: 3, mbtiJP: 2, discD: 4, discI: 4, discS: 2, discC: 4, big5O: 5, big5C: 4, big5E: 4, big5A: 4, big5N: 3, jobCollar: "arts" },
  { roleNumber: 121, roleName: "Editor", mbtiEI: 3, mbtiSN: 2, mbtiTF: 4, mbtiJP: 4, discD: 4, discI: 3, discS: 3, discC: 5, big5O: 5, big5C: 5, big5E: 3, big5A: 3, big5N: 2, jobCollar: "white" },
  { roleNumber: 122, roleName: "Broadcast Technician", mbtiEI: 3, mbtiSN: 4, mbtiTF: 4, mbtiJP: 3, discD: 3, discI: 3, discS: 4, discC: 4, big5O: 3, big5C: 5, big5E: 3, big5A: 3, big5N: 2, jobCollar: "white" },
  { roleNumber: 123, roleName: "Agricultural Worker", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 2, discI: 2, discS: 5, discC: 3, big5O: 2, big5C: 4, big5E: 3, big5A: 4, big5N: 2, jobCollar: "blue" },
  { roleNumber: 124, roleName: "Mining Worker", mbtiEI: 2, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 4, discI: 2, discS: 4, discC: 3, big5O: 2, big5C: 4, big5E: 2, big5A: 3, big5N: 4, jobCollar: "blue" },
  { roleNumber: 125, roleName: "Oil Rig Worker", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 4, discI: 3, discS: 4, discC: 3, big5O: 2, big5C: 4, big5E: 3, big5A: 3, big5N: 4, jobCollar: "blue" },
  { roleNumber: 126, roleName: "Computer Support Specialist", mbtiEI: 4, mbtiSN: 3, mbtiTF: 4, mbtiJP: 4, discD: 3, discI: 4, discS: 4, discC: 4, big5O: 3, big5C: 5, big5E: 4, big5A: 4, big5N: 3, jobCollar: "white" },
  { roleNumber: 127, roleName: "Network Administrator", mbtiEI: 3, mbtiSN: 3, mbtiTF: 5, mbtiJP: 4, discD: 4, discI: 3, discS: 3, discC: 5, big5O: 3, big5C: 5, big5E: 3, big5A: 3, big5N: 2, jobCollar: "white" },
  { roleNumber: 128, roleName: "Actuary", mbtiEI: 2, mbtiSN: 2, mbtiTF: 5, mbtiJP: 5, discD: 3, discI: 2, discS: 2, discC: 5, big5O: 3, big5C: 5, big5E: 2, big5A: 3, big5N: 2, jobCollar: "white" },
  { roleNumber: 129, roleName: "Market Research Analyst", mbtiEI: 3, mbtiSN: 2, mbtiTF: 5, mbtiJP: 4, discD: 4, discI: 3, discS: 3, discC: 5, big5O: 4, big5C: 5, big5E: 3, big5A: 3, big5N: 2, jobCollar: "white" },
  { roleNumber: 130, roleName: "Loan Officer", mbtiEI: 4, mbtiSN: 3, mbtiTF: 4, mbtiJP: 5, discD: 4, discI: 4, discS: 3, discC: 4, big5O: 3, big5C: 5, big5E: 4, big5A: 4, big5N: 3, jobCollar: "white" },
  { roleNumber: 131, roleName: "Management Analyst", mbtiEI: 4, mbtiSN: 2, mbtiTF: 5, mbtiJP: 4, discD: 5, discI: 4, discS: 3, discC: 4, big5O: 4, big5C: 5, big5E: 4, big5A: 3, big5N: 3, jobCollar: "white" },
  { roleNumber: 132, roleName: "Logisticians", mbtiEI: 3, mbtiSN: 3, mbtiTF: 5, mbtiJP: 5, discD: 4, discI: 3, discS: 4, discC: 5, big5O: 3, big5C: 5, big5E: 3, big5A: 3, big5N: 2, jobCollar: "white" },
  { roleNumber: 133, roleName: "Substance Abuse Counselor", mbtiEI: 4, mbtiSN: 3, mbtiTF: 2, mbtiJP: 4, discD: 3, discI: 5, discS: 5, discC: 3, big5O: 4, big5C: 4, big5E: 4, big5A: 5, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 134, roleName: "Probation Officer", mbtiEI: 4, mbtiSN: 4, mbtiTF: 4, mbtiJP: 5, discD: 5, discI: 4, discS: 4, discC: 4, big5O: 3, big5C: 5, big5E: 4, big5A: 4, big5N: 4, jobCollar: "service" },
  { roleNumber: 135, roleName: "Pest Control Worker", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 3, discI: 3, discS: 4, discC: 4, big5O: 2, big5C: 4, big5E: 3, big5A: 3, big5N: 3, jobCollar: "service" },
  { roleNumber: 136, roleName: "Air Traffic Controller", mbtiEI: 3, mbtiSN: 4, mbtiTF: 5, mbtiJP: 5, discD: 5, discI: 3, discS: 3, discC: 5, big5O: 3, big5C: 5, big5E: 3, big5A: 3, big5N: 5, jobCollar: "white" },
  { roleNumber: 137, roleName: "Aircraft Mechanic", mbtiEI: 2, mbtiSN: 5, mbtiTF: 4, mbtiJP: 4, discD: 3, discI: 2, discS: 4, discC: 5, big5O: 3, big5C: 5, big5E: 2, big5A: 3, big5N: 3, jobCollar: "blue" },
  { roleNumber: 138, roleName: "Boilermaker", mbtiEI: 2, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 4, discI: 2, discS: 4, discC: 4, big5O: 2, big5C: 5, big5E: 2, big5A: 3, big5N: 3, jobCollar: "blue" },
  { roleNumber: 139, roleName: "Elevator Installer/Repairer", mbtiEI: 3, mbtiSN: 5, mbtiTF: 4, mbtiJP: 4, discD: 3, discI: 2, discS: 4, discC: 4, big5O: 2, big5C: 5, big5E: 3, big5A: 3, big5N: 3, jobCollar: "blue" },
  { roleNumber: 140, roleName: "Sheet Metal Worker", mbtiEI: 2, mbtiSN: 5, mbtiTF: 4, mbtiJP: 3, discD: 3, discI: 2, discS: 4, discC: 4, big5O: 3, big5C: 5, big5E: 2, big5A: 3, big5N: 2, jobCollar: "blue" },
  { roleNumber: 141, roleName: "Power Plant Operator", mbtiEI: 2, mbtiSN: 5, mbtiTF: 4, mbtiJP: 5, discD: 4, discI: 2, discS: 4, discC: 5, big5O: 2, big5C: 5, big5E: 2, big5A: 3, big5N: 3, jobCollar: "blue" },
  { roleNumber: 142, roleName: "Water Treatment Operator", mbtiEI: 2, mbtiSN: 5, mbtiTF: 4, mbtiJP: 5, discD: 3, discI: 2, discS: 4, discC: 5, big5O: 2, big5C: 5, big5E: 2, big5A: 3, big5N: 3, jobCollar: "blue" },
  { roleNumber: 143, roleName: "Bakers", mbtiEI: 3, mbtiSN: 5, mbtiTF: 3, mbtiJP: 3, discD: 3, discI: 3, discS: 4, discC: 4, big5O: 3, big5C: 4, big5E: 3, big5A: 3, big5N: 2, jobCollar: "service" },
  { roleNumber: 144, roleName: "Quality Control Inspector", mbtiEI: 2, mbtiSN: 5, mbtiTF: 5, mbtiJP: 5, discD: 3, discI: 2, discS: 4, discC: 5, big5O: 2, big5C: 5, big5E: 2, big5A: 3, big5N: 2, jobCollar: "blue" },
  { roleNumber: 145, roleName: "Dental Assistant", mbtiEI: 4, mbtiSN: 5, mbtiTF: 3, mbtiJP: 4, discD: 3, discI: 4, discS: 5, discC: 4, big5O: 2, big5C: 5, big5E: 4, big5A: 5, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 146, roleName: "Massage Therapist", mbtiEI: 4, mbtiSN: 4, mbtiTF: 2, mbtiJP: 3, discD: 3, discI: 4, discS: 5, discC: 3, big5O: 4, big5C: 4, big5E: 4, big5A: 5, big5N: 3, jobCollar: "healthcare" },
  { roleNumber: 147, roleName: "Recreation Worker", mbtiEI: 5, mbtiSN: 4, mbtiTF: 2, mbtiJP: 3, discD: 4, discI: 5, discS: 4, discC: 3, big5O: 4, big5C: 4, big5E: 5, big5A: 5, big5N: 3, jobCollar: "service" },
  { roleNumber: 148, roleName: "Podcaster (side hustle)", mbtiEI: 4, mbtiSN: 2, mbtiTF: 3, mbtiJP: 2, discD: 4, discI: 5, discS: 2, discC: 3, big5O: 5, big5C: 4, big5E: 4, big5A: 4, big5N: 3, jobCollar: "arts" },
  { roleNumber: 149, roleName: "Blogger", mbtiEI: 3, mbtiSN: 2, mbtiTF: 3, mbtiJP: 2, discD: 3, discI: 4, discS: 2, discC: 4, big5O: 5, big5C: 4, big5E: 3, big5A: 4, big5N: 2, jobCollar: "arts" },
  { roleNumber: 150, roleName: "Interpreter/Translator", mbtiEI: 3, mbtiSN: 3, mbtiTF: 3, mbtiJP: 4, discD: 3, discI: 4, discS: 4, discC: 4, big5O: 4, big5C: 5, big5E: 3, big5A: 5, big5N: 2, jobCollar: "white" },
];

export async function seedJobRoles() {
  console.log("Seeding job roles...");
  
  try {
    const existingRoles = await db.select().from(jobRoles).limit(1);
    if (existingRoles.length > 0) {
      console.log("Job roles already seeded, skipping...");
      return;
    }
    
    for (const role of JOB_ROLES_DATA) {
      await db.insert(jobRoles).values(role);
    }
    
    console.log(`Successfully seeded ${JOB_ROLES_DATA.length} job roles`);
  } catch (error) {
    console.error("Error seeding job roles:", error);
    throw error;
  }
}
