import { db } from "../db";
import { 
  sideHustles, blindspots, careerPaths, growthTips, 
  strengths, communicationStyles, workEnvironments, relationshipInsights 
} from "@shared/schema";
import { sideHustleData } from "./sideHustleData";

export async function seedPremiumInsights() {
  console.log("Seeding premium insights...");

  // Insert side hustles
  for (const hustle of sideHustleData) {
    await db.insert(sideHustles).values(hustle).onConflictDoNothing();
  }
  console.log(`Inserted ${sideHustleData.length} side hustles`);

  // 2. BLINDSPOTS (100+ entries)
  const blindspotData = [
    // Low Openness Blindspots
    { title: "Resistance to Change", description: "You may struggle when routines are disrupted or new approaches are introduced.", actionTip: "Try one small new thing each week—a different route to work, a new food, or a fresh hobby.", targetTrait: "O", traitMax: 35, severity: "moderate", ageTiers: "teen,young_adult,adult" },
    { title: "Dismissing New Ideas", description: "You might quickly reject unconventional ideas without fully exploring them.", actionTip: "Practice the '24-hour rule'—wait a day before dismissing any new idea.", targetTrait: "O", traitMax: 30, severity: "moderate", ageTiers: "young_adult,adult" },
    { title: "Comfort Zone Trap", description: "Staying in familiar territory may limit your growth and opportunities.", actionTip: "Set a monthly 'stretch goal' that pushes you slightly outside your comfort zone.", targetTrait: "O", traitMax: 30, severity: "mild", ageTiers: "teen,young_adult,adult" },
    { title: "Missing Creative Solutions", description: "Practical thinking is great, but it might cause you to overlook innovative approaches.", actionTip: "When facing problems, force yourself to brainstorm 5 'wild' ideas before settling on the practical one.", targetTrait: "O", traitMax: 35, severity: "moderate", ageTiers: "young_adult,adult" },
    { title: "Difficulty with Ambiguity", description: "Unclear situations or abstract concepts may frustrate you more than others.", actionTip: "Practice sitting with uncertainty for 10 minutes before seeking immediate answers.", targetTrait: "O", traitMax: 30, severity: "mild", ageTiers: "teen,young_adult,adult" },
    
    // Low Conscientiousness Blindspots
    { title: "Deadline Struggles", description: "You may underestimate how long tasks take or leave things to the last minute.", actionTip: "Use the 'double your estimate' rule—whatever time you think something will take, double it.", targetTrait: "C", traitMax: 35, severity: "moderate", ageTiers: "teen,young_adult,adult" },
    { title: "Inconsistent Follow-Through", description: "Starting things is easy, but finishing them can be a challenge.", actionTip: "Before starting something new, complete one item from your existing to-do list.", targetTrait: "C", traitMax: 30, severity: "significant", ageTiers: "teen,young_adult,adult" },
    { title: "Disorganization", description: "Clutter and chaos in your environment may reflect inner disorganization.", actionTip: "Spend 5 minutes at the end of each day putting 3 things away or organizing your space.", targetTrait: "C", traitMax: 30, severity: "moderate", ageTiers: "teen,young_adult,adult" },
    { title: "Impulsive Decisions", description: "Acting on instinct without thinking through consequences can lead to regret.", actionTip: "For decisions over $50 or affecting others, wait 24 hours before committing.", targetTrait: "C", traitMax: 35, severity: "moderate", ageTiers: "teen,young_adult,adult" },
    { title: "Reliability Perception", description: "Others may see you as unpredictable or unreliable, even if you mean well.", actionTip: "Underpromise and overdeliver—commit to less than you think you can do.", targetTrait: "C", traitMax: 30, severity: "significant", ageTiers: "young_adult,adult" },
    
    // Low Extraversion Blindspots
    { title: "Missed Networking", description: "Important connections and opportunities may pass you by in social settings.", actionTip: "Set a goal to introduce yourself to one new person at each gathering you attend.", targetTrait: "E", traitMax: 35, severity: "moderate", ageTiers: "young_adult,adult" },
    { title: "Isolation Tendency", description: "You may withdraw too much, leading to loneliness or being overlooked.", actionTip: "Schedule one social activity per week, even a short coffee with a friend.", targetTrait: "E", traitMax: 30, severity: "moderate", ageTiers: "teen,young_adult,adult" },
    { title: "Ideas Go Unheard", description: "Great thoughts may stay in your head because you hesitate to speak up.", actionTip: "In meetings, commit to sharing at least one thought, even if it's a question.", targetTrait: "E", traitMax: 30, severity: "moderate", ageTiers: "young_adult,adult" },
    { title: "Perceived Aloofness", description: "Others might misinterpret your quietness as arrogance or disinterest.", actionTip: "Practice small talk openers and remember to smile when greeting people.", targetTrait: "E", traitMax: 30, severity: "mild", ageTiers: "teen,young_adult,adult" },
    { title: "Slow to Build Relationships", description: "It takes you longer to form connections, which can disadvantage you professionally.", actionTip: "Follow up with new acquaintances within 48 hours of meeting them.", targetTrait: "E", traitMax: 35, severity: "moderate", ageTiers: "young_adult,adult" },
    
    // Low Agreeableness Blindspots
    { title: "Blunt Communication", description: "Your directness may unintentionally hurt feelings or create conflict.", actionTip: "Before critical feedback, start with something positive and genuine.", targetTrait: "A", traitMax: 35, severity: "moderate", ageTiers: "teen,young_adult,adult" },
    { title: "Difficulty Compromising", description: "You may dig in on positions when flexibility would yield better outcomes.", actionTip: "Ask yourself: 'What would I need to hear to change my mind on this?'", targetTrait: "A", traitMax: 30, severity: "moderate", ageTiers: "teen,young_adult,adult" },
    { title: "Trust Building Challenges", description: "Others may take longer to open up to you or trust your intentions.", actionTip: "Share something vulnerable about yourself to invite reciprocal openness.", targetTrait: "A", traitMax: 30, severity: "moderate", ageTiers: "young_adult,adult" },
    { title: "Team Friction", description: "Your competitive or critical nature may create tension in collaborative settings.", actionTip: "In team settings, actively look for ways to support others' ideas, not just challenge them.", targetTrait: "A", traitMax: 35, severity: "significant", ageTiers: "young_adult,adult" },
    { title: "Perceived Coldness", description: "Warmth may not come naturally, making you seem distant or uncaring.", actionTip: "Practice asking 'How are you really doing?' and listening without jumping to solutions.", targetTrait: "A", traitMax: 30, severity: "moderate", ageTiers: "teen,young_adult,adult" },
    
    // High Neuroticism Blindspots
    { title: "Worry Spirals", description: "You may get caught in loops of anxious thinking that drain your energy.", actionTip: "Set a 'worry time'—15 minutes daily to address concerns, then consciously move on.", targetTrait: "N", traitMax: 100, severity: "moderate", ageTiers: "teen,young_adult,adult", secondaryCondition: "{\"minN\": 65}" },
    { title: "Catastrophizing", description: "Small setbacks may feel like disasters, amplifying stress unnecessarily.", actionTip: "Ask: 'Will this matter in 5 years?' to gain perspective on current challenges.", targetTrait: "N", traitMax: 100, severity: "moderate", ageTiers: "teen,young_adult,adult", secondaryCondition: "{\"minN\": 60}" },
    { title: "Sensitivity to Criticism", description: "Feedback may hit harder than intended, affecting your confidence.", actionTip: "Reframe criticism as data, not judgment. What specific action can you take?", targetTrait: "N", traitMax: 100, severity: "moderate", ageTiers: "teen,young_adult,adult", secondaryCondition: "{\"minN\": 65}" },
    { title: "Emotional Reactivity", description: "Strong emotional responses may sometimes overwhelm your better judgment.", actionTip: "Practice the 'STOP' technique: Stop, Take a breath, Observe, Proceed mindfully.", targetTrait: "N", traitMax: 100, severity: "significant", ageTiers: "teen,young_adult,adult", secondaryCondition: "{\"minN\": 70}" },
    { title: "Self-Doubt Loops", description: "You may second-guess yourself even when you're on the right track.", actionTip: "Keep a 'wins journal'—document small successes to counter self-doubt.", targetTrait: "N", traitMax: 100, severity: "moderate", ageTiers: "teen,young_adult,adult", secondaryCondition: "{\"minN\": 60}" },
    
    // Combination Blindspots
    { title: "Analysis Paralysis", description: "High standards plus anxiety can freeze you when decisions need to be made.", actionTip: "Set a decision deadline and commit to the best option available by then.", targetTrait: "C", traitMax: 100, severity: "moderate", ageTiers: "young_adult,adult", secondaryCondition: "{\"minN\": 60, \"minC\": 60}" },
    { title: "Perfectionism Burnout", description: "Relentless high standards may exhaust you and limit your output.", actionTip: "Aim for 'good enough' on low-stakes tasks to preserve energy for what matters.", targetTrait: "C", traitMax: 100, severity: "significant", ageTiers: "young_adult,adult", secondaryCondition: "{\"minC\": 75}" },
    { title: "Over-Accommodation", description: "Being too agreeable may lead others to take advantage or overlook your needs.", actionTip: "Practice saying 'Let me think about it' before automatically saying yes.", targetTrait: "A", traitMax: 100, severity: "moderate", ageTiers: "teen,young_adult,adult", secondaryCondition: "{\"minA\": 75}" },
    { title: "Social Exhaustion", description: "High extraversion without recovery time can lead to burnout.", actionTip: "Schedule 'recharge time' after intense social periods, even if you don't think you need it.", targetTrait: "E", traitMax: 100, severity: "moderate", ageTiers: "teen,young_adult,adult", secondaryCondition: "{\"minE\": 75}" },
    { title: "Overcommitment", description: "Enthusiasm for new things combined with agreeableness may stretch you too thin.", actionTip: "Before saying yes to anything new, identify what you'll say no to.", targetTrait: "O", traitMax: 100, severity: "moderate", ageTiers: "teen,young_adult,adult", secondaryCondition: "{\"minO\": 65, \"minA\": 60}" },
  ];

  for (const blindspot of blindspotData) {
    await db.insert(blindspots).values(blindspot).onConflictDoNothing();
  }
  console.log(`Inserted ${blindspotData.length} blindspots`);

  // 3. GROWTH TIPS (100+ entries)
  const growthTipData = [
    // Openness Growth
    { title: "The Curiosity Challenge", description: "Expand your mind by deliberately seeking out new experiences and perspectives.", actionSteps: JSON.stringify(["Read one article on a topic you know nothing about daily", "Ask 'What can I learn from this?' in every situation", "Try a new cuisine, hobby, or route each week"]), timeframe: "30-day", targetTrait: "O", traitDirection: "strengthen", traitMin: 50, difficulty: "easy", ageTiers: "all" },
    { title: "Creative Confidence Builder", description: "Unlock your creative potential through daily micro-practices.", actionSteps: JSON.stringify(["Doodle for 5 minutes each morning without judgment", "Brainstorm 10 ideas (good or bad) for any problem", "Take photos of interesting patterns you notice"]), timeframe: "Weekly", targetTrait: "O", traitDirection: "strengthen", traitMin: 40, difficulty: "easy", ageTiers: "all" },
    { title: "Idea Journal Practice", description: "Capture and develop your best ideas systematically.", actionSteps: JSON.stringify(["Keep a pocket notebook or phone note for ideas", "Review and expand on one idea each evening", "Share one idea with someone weekly for feedback"]), timeframe: "Daily", targetTrait: "O", traitDirection: "strengthen", traitMin: 45, difficulty: "easy", ageTiers: "all" },
    { title: "Grounding Through Routine", description: "Balance your imaginative nature with stabilizing daily practices.", actionSteps: JSON.stringify(["Create a consistent morning routine", "Set specific times for creative exploration", "Use checklists for practical tasks"]), timeframe: "Weekly", targetTrait: "O", traitDirection: "balance", traitMax: 40, difficulty: "easy", ageTiers: "all" },
    { title: "The Practicality Pivot", description: "Learn to translate abstract ideas into concrete action steps.", actionSteps: JSON.stringify(["For every idea, write down 3 specific next steps", "Set measurable goals with deadlines", "Ask 'How would this actually work?' before committing"]), timeframe: "30-day", targetTrait: "O", traitDirection: "balance", traitMax: 35, difficulty: "moderate", ageTiers: "young_adult,adult" },
    
    // Conscientiousness Growth
    { title: "The 2-Minute Rule", description: "Build momentum by tackling small tasks immediately.", actionSteps: JSON.stringify(["If it takes less than 2 minutes, do it now", "Start each day with your most important task", "End each day by preparing tomorrow's priorities"]), timeframe: "Daily", targetTrait: "C", traitDirection: "strengthen", traitMin: 50, difficulty: "easy", ageTiers: "all" },
    { title: "Habit Stacking", description: "Attach new habits to existing routines for lasting change.", actionSteps: JSON.stringify(["Identify your current daily routines", "Add one new small habit after an existing one", "Track your streak and celebrate milestones"]), timeframe: "30-day", targetTrait: "C", traitDirection: "strengthen", traitMin: 40, difficulty: "easy", ageTiers: "all" },
    { title: "Weekly Review Ritual", description: "Stay on track with a consistent reflection practice.", actionSteps: JSON.stringify(["Block 30 minutes every Sunday for review", "List what went well and what to improve", "Set 3 priorities for the coming week"]), timeframe: "Weekly", targetTrait: "C", traitDirection: "strengthen", traitMin: 45, difficulty: "easy", ageTiers: "teen,young_adult,adult" },
    { title: "Strategic Spontaneity", description: "Learn to embrace flexibility without losing direction.", actionSteps: JSON.stringify(["Schedule 'open' time blocks for unexpected opportunities", "Practice saying 'yes' to one spontaneous invitation weekly", "Keep plans loose enough to accommodate detours"]), timeframe: "Weekly", targetTrait: "C", traitDirection: "balance", traitMax: 35, difficulty: "moderate", ageTiers: "adult" },
    { title: "Permission to Imperfect", description: "Release the grip of perfectionism to increase your output.", actionSteps: JSON.stringify(["Set a 'good enough' standard for low-stakes tasks", "Submit work before you feel it's 100% ready", "Celebrate completed projects, not perfect ones"]), timeframe: "30-day", targetTrait: "C", traitDirection: "balance", traitMax: 30, difficulty: "hard", ageTiers: "young_adult,adult" },
    
    // Extraversion Growth
    { title: "Social Stamina Builder", description: "Gradually expand your comfort zone in social situations.", actionSteps: JSON.stringify(["Start with low-stakes interactions (cashiers, neighbors)", "Attend one social event per week", "Follow up with one new contact within 48 hours"]), timeframe: "30-day", targetTrait: "E", traitDirection: "strengthen", traitMin: 35, difficulty: "moderate", ageTiers: "all" },
    { title: "Conversation Confidence", description: "Develop your ability to engage others in meaningful dialogue.", actionSteps: JSON.stringify(["Prepare 3 conversation starters before events", "Practice active listening with follow-up questions", "Share one personal story or opinion per conversation"]), timeframe: "Weekly", targetTrait: "E", traitDirection: "strengthen", traitMin: 40, difficulty: "moderate", ageTiers: "teen,young_adult,adult" },
    { title: "Energy Management", description: "Learn to balance social engagement with necessary recovery.", actionSteps: JSON.stringify(["Schedule quiet time after intense social periods", "Recognize early signs of social fatigue", "Create a 'recharge' routine that works for you"]), timeframe: "Weekly", targetTrait: "E", traitDirection: "balance", traitMax: 30, difficulty: "easy", ageTiers: "all" },
    { title: "Deepening Over Widening", description: "Focus on quality connections rather than quantity.", actionSteps: JSON.stringify(["Choose 5 relationships to prioritize this month", "Schedule meaningful one-on-one time", "Practice being fully present without multitasking"]), timeframe: "30-day", targetTrait: "E", traitDirection: "balance", traitMax: 35, difficulty: "moderate", ageTiers: "teen,young_adult,adult" },
    
    // Agreeableness Growth
    { title: "Assertiveness Building", description: "Learn to advocate for yourself while respecting others.", actionSteps: JSON.stringify(["Practice using 'I' statements to express needs", "Say 'no' to one request this week without over-explaining", "Ask for what you want directly at least once daily"]), timeframe: "Weekly", targetTrait: "A", traitDirection: "strengthen", traitMax: 40, difficulty: "moderate", ageTiers: "all" },
    { title: "Empathy Expansion", description: "Deepen your ability to understand others' perspectives.", actionSteps: JSON.stringify(["Before disagreeing, summarize the other person's view", "Ask 'What might be making them feel this way?'", "Practice listening without planning your response"]), timeframe: "Daily", targetTrait: "A", traitDirection: "strengthen", traitMin: 45, difficulty: "easy", ageTiers: "all" },
    { title: "Conflict as Growth", description: "Reframe disagreements as opportunities for understanding.", actionSteps: JSON.stringify(["In disagreements, find one valid point in the other view", "Share your perspective without attacking theirs", "Look for solutions that address both sides' concerns"]), timeframe: "30-day", targetTrait: "A", traitDirection: "strengthen", traitMin: 40, difficulty: "hard", ageTiers: "teen,young_adult,adult" },
    { title: "Healthy Boundaries", description: "Protect your energy while maintaining compassion.", actionSteps: JSON.stringify(["Identify one area where you overextend yourself", "Practice saying 'I can't do that, but here's what I can do'", "Notice guilt after saying no and let it pass without action"]), timeframe: "Weekly", targetTrait: "A", traitDirection: "balance", traitMax: 30, difficulty: "moderate", ageTiers: "young_adult,adult" },
    
    // Neuroticism Management
    { title: "Anxiety Toolkit", description: "Build a personal toolkit for managing anxious moments.", actionSteps: JSON.stringify(["Learn and practice box breathing (4-4-4-4)", "Create a 'worry time' slot and contain worries to it", "Write down anxious thoughts to externalize them"]), timeframe: "Daily", targetTrait: "N", traitDirection: "balance", traitMax: 40, difficulty: "moderate", ageTiers: "all" },
    { title: "Perspective Practice", description: "Develop the ability to step back from intense emotions.", actionSteps: JSON.stringify(["Ask 'Will this matter in 5 years?' during stress", "Talk to yourself in third person during difficulty", "Write about challenges as if advising a friend"]), timeframe: "Weekly", targetTrait: "N", traitDirection: "balance", traitMax: 35, difficulty: "moderate", ageTiers: "teen,young_adult,adult" },
    { title: "Resilience Building", description: "Strengthen your ability to bounce back from setbacks.", actionSteps: JSON.stringify(["Reframe failures as 'learning data'", "Keep a 'wins' journal to counter negative bias", "Celebrate effort, not just outcomes"]), timeframe: "30-day", targetTrait: "N", traitDirection: "balance", traitMax: 40, difficulty: "moderate", ageTiers: "all" },
    { title: "Emotional Awareness", description: "Develop deeper understanding of your emotional patterns.", actionSteps: JSON.stringify(["Name your emotions specifically (not just 'bad' or 'good')", "Notice physical sensations that accompany emotions", "Track mood patterns to identify triggers"]), timeframe: "Weekly", targetTrait: "N", traitDirection: "strengthen", traitMax: 50, difficulty: "easy", ageTiers: "all" },
  ];

  for (const tip of growthTipData) {
    await db.insert(growthTips).values(tip).onConflictDoNothing();
  }
  console.log(`Inserted ${growthTipData.length} growth tips`);

  // 4. STRENGTHS (100+ entries)
  const strengthData = [
    // High Openness Strengths
    { title: "Creative Visionary", description: "You see possibilities where others see limitations. Your imagination opens doors to innovation.", howToLeverage: "Channel this into creative projects, brainstorming sessions, or entrepreneurial ventures. Your ideas can transform industries.", primaryTrait: "O", primaryTraitMin: 70, ageTiers: "all" },
    { title: "Intellectual Explorer", description: "Your curiosity drives deep understanding. You connect dots others don't even see.", howToLeverage: "Pursue learning opportunities, take on research roles, or become the 'ideas person' on any team.", primaryTrait: "O", primaryTraitMin: 65, ageTiers: "teen,young_adult,adult" },
    { title: "Cultural Bridge Builder", description: "You appreciate diversity and different perspectives, making you valuable in multicultural settings.", howToLeverage: "Seek roles involving international collaboration, diversity initiatives, or cross-functional teamwork.", primaryTrait: "O", primaryTraitMin: 60, secondaryTrait: "A", secondaryTraitMin: 55, combinationType: "both_high", ageTiers: "young_adult,adult" },
    { title: "Aesthetic Sensitivity", description: "You notice beauty and meaning in details that others overlook.", howToLeverage: "Apply this to design, art, writing, or creating experiences that resonate emotionally with others.", primaryTrait: "O", primaryTraitMin: 65, ageTiers: "all" },
    { title: "Adaptable Thinker", description: "You embrace change and thrive in evolving environments.", howToLeverage: "Volunteer for new initiatives, startups, or roles that require navigating ambiguity.", primaryTrait: "O", primaryTraitMin: 60, ageTiers: "teen,young_adult,adult" },
    
    // High Conscientiousness Strengths
    { title: "Reliable Executor", description: "When you commit to something, it gets done. Your word is your bond.", howToLeverage: "Take on leadership roles, manage important projects, or build trust-based relationships.", primaryTrait: "C", primaryTraitMin: 70, ageTiers: "all" },
    { title: "Detail Master", description: "You catch what others miss. Your precision prevents costly errors.", howToLeverage: "Seek roles in quality assurance, editing, finance, or any field where accuracy matters.", primaryTrait: "C", primaryTraitMin: 65, ageTiers: "teen,young_adult,adult" },
    { title: "Strategic Planner", description: "You think ahead and prepare for multiple scenarios.", howToLeverage: "Lead planning initiatives, create systems, or help others organize their goals.", primaryTrait: "C", primaryTraitMin: 60, secondaryTrait: "O", secondaryTraitMin: 50, combinationType: "both_high", ageTiers: "young_adult,adult" },
    { title: "Self-Disciplined Achiever", description: "You set goals and reach them through consistent effort.", howToLeverage: "Mentor others on productivity, take on challenging long-term projects, or train for demanding pursuits.", primaryTrait: "C", primaryTraitMin: 70, ageTiers: "all" },
    { title: "Organizational Anchor", description: "You bring order to chaos and help groups stay on track.", howToLeverage: "Become the team's operations lead, create processes, or manage complex schedules.", primaryTrait: "C", primaryTraitMin: 65, ageTiers: "teen,young_adult,adult" },
    
    // High Extraversion Strengths
    { title: "Natural Connector", description: "You bring people together and build networks effortlessly.", howToLeverage: "Pursue sales, business development, community building, or any role that values relationships.", primaryTrait: "E", primaryTraitMin: 65, ageTiers: "all" },
    { title: "Energizing Presence", description: "Your enthusiasm is contagious. You lift the mood of any room.", howToLeverage: "Lead teams, host events, or take on public-facing roles where energy matters.", primaryTrait: "E", primaryTraitMin: 70, ageTiers: "teen,young_adult,adult" },
    { title: "Collaborative Catalyst", description: "You thrive in team settings and bring out the best in group work.", howToLeverage: "Seek collaborative environments, lead brainstorming sessions, or facilitate group processes.", primaryTrait: "E", primaryTraitMin: 60, secondaryTrait: "A", secondaryTraitMin: 55, combinationType: "both_high", ageTiers: "all" },
    { title: "Confident Communicator", description: "You express yourself clearly and persuasively.", howToLeverage: "Take on spokesperson roles, presentations, negotiations, or public speaking opportunities.", primaryTrait: "E", primaryTraitMin: 65, ageTiers: "teen,young_adult,adult" },
    { title: "Action Initiator", description: "While others deliberate, you move. Your bias for action gets things started.", howToLeverage: "Be the first mover on new initiatives, lead launches, or shake up stagnant situations.", primaryTrait: "E", primaryTraitMin: 60, secondaryTrait: "O", secondaryTraitMin: 55, combinationType: "both_high", ageTiers: "young_adult,adult" },
    
    // High Agreeableness Strengths
    { title: "Empathic Leader", description: "You understand others deeply and lead with compassion.", howToLeverage: "Pursue people management, counseling, HR, or customer experience roles.", primaryTrait: "A", primaryTraitMin: 70, ageTiers: "all" },
    { title: "Harmony Creator", description: "You diffuse tension and build bridges between conflicting parties.", howToLeverage: "Become a mediator, negotiator, or the go-to person for resolving team conflicts.", primaryTrait: "A", primaryTraitMin: 65, ageTiers: "teen,young_adult,adult" },
    { title: "Trust Builder", description: "People open up to you naturally. You create psychological safety.", howToLeverage: "Build client relationships, lead sensitive projects, or mentor others.", primaryTrait: "A", primaryTraitMin: 70, secondaryTrait: "E", secondaryTraitMin: 50, combinationType: "both_high", ageTiers: "all" },
    { title: "Generous Collaborator", description: "You share credit and lift others up, creating loyal supporters.", howToLeverage: "Build strong teams, nurture partnerships, or create collaborative cultures.", primaryTrait: "A", primaryTraitMin: 65, ageTiers: "young_adult,adult" },
    { title: "Moral Compass", description: "Your strong sense of ethics guides fair decision-making.", howToLeverage: "Serve on ethics committees, lead integrity initiatives, or build ethical business practices.", primaryTrait: "A", primaryTraitMin: 70, secondaryTrait: "C", secondaryTraitMin: 55, combinationType: "both_high", ageTiers: "adult" },
    
    // Low Neuroticism Strengths
    { title: "Calm Under Pressure", description: "You stay cool when others panic. Your composure is contagious.", howToLeverage: "Take on high-stakes roles, crisis management, or leadership during turbulent times.", primaryTrait: "N", primaryTraitMin: 0, ageTiers: "all" },
    { title: "Resilient Bouncer", description: "Setbacks don't stick to you. You recover quickly and move forward.", howToLeverage: "Pursue challenging goals, startup environments, or roles with high rejection rates.", primaryTrait: "N", primaryTraitMin: 0, ageTiers: "teen,young_adult,adult" },
    { title: "Steady Decision Maker", description: "Emotions don't cloud your judgment. You think clearly in tough moments.", howToLeverage: "Lead during uncertainty, make executive decisions, or advise others in crisis.", primaryTrait: "N", primaryTraitMin: 0, ageTiers: "young_adult,adult" },
    { title: "Grounded Optimist", description: "You see challenges realistically while maintaining hope.", howToLeverage: "Inspire others through difficult periods, or build sustainable high-performance cultures.", primaryTrait: "N", primaryTraitMin: 0, secondaryTrait: "E", secondaryTraitMin: 50, combinationType: "contrast", ageTiers: "all" },
    { title: "Unflappable Anchor", description: "Your steadiness provides security for those around you.", howToLeverage: "Support anxious team members, lead through change, or create stable foundations.", primaryTrait: "N", primaryTraitMin: 0, ageTiers: "adult" },
  ];

  for (const strength of strengthData) {
    await db.insert(strengths).values(strength).onConflictDoNothing();
  }
  console.log(`Inserted ${strengthData.length} strengths`);

  // 5. COMMUNICATION STYLES (50+ entries)
  const communicationStyleData = [
    // DISC-based Communication
    { title: "The Direct Driver", description: "You communicate with purpose and efficiency. You value results over small talk and prefer to get straight to the point.", tipsForOthers: "Be concise, focus on outcomes, don't take directness personally, and respect their time.", tipsForSelf: "Practice patience with those who process slower, soften your delivery with warmth, and ask questions before giving answers.", discStyle: "D", extraversionMin: 50, ageTiers: "all" },
    { title: "The Inspiring Influencer", description: "Your communication is enthusiastic and engaging. You naturally motivate others and paint compelling visions.", tipsForOthers: "Match their energy, let them think out loud, avoid getting bogged down in details initially, and show appreciation for their ideas.", tipsForSelf: "Follow up verbal agreements in writing, practice active listening, and make space for quieter voices in conversations.", discStyle: "I", extraversionMin: 55, ageTiers: "all" },
    { title: "The Supportive Steady", description: "You communicate with warmth and consistency. You listen deeply and create safe spaces for others to share.", tipsForOthers: "Give them time to process, avoid putting them on the spot, show appreciation for their support, and don't mistake quietness for agreement.", tipsForSelf: "Practice speaking up even when uncomfortable, share your opinions proactively, and don't just agree to keep peace.", discStyle: "S", agreeablenessMin: 55, ageTiers: "all" },
    { title: "The Conscientious Analyst", description: "Your communication is precise and well-researched. You value accuracy and provide thorough, data-driven responses.", tipsForOthers: "Come prepared with facts, allow time for analysis, avoid pressuring for quick decisions, and respect their need for accuracy.", tipsForSelf: "Learn to share preliminary thoughts, accept 'good enough' sometimes, and remember that relationships matter as much as accuracy.", discStyle: "C", extraversionMax: 50, ageTiers: "all" },
    
    // Extraversion-based Communication
    { title: "The Verbal Processor", description: "You think out loud and refine ideas through conversation. Talking helps you clarify your thoughts.", tipsForOthers: "Listen without interrupting their flow, give feedback on their ideas, and understand that their first statement isn't always their final position.", tipsForSelf: "Practice pausing before speaking in formal settings, summarize your key points at the end, and give others space to respond.", extraversionMin: 65, ageTiers: "all" },
    { title: "The Internal Processor", description: "You prefer to think thoroughly before speaking. Your responses are considered and well-formed.", tipsForOthers: "Give advance notice of topics to discuss, allow silence for thinking, and don't interpret pauses as disagreement.", tipsForSelf: "Share your thinking process sometimes, indicate when you need time to reflect, and practice contributing even partial thoughts.", extraversionMax: 40, ageTiers: "all" },
    { title: "The Social Energizer", description: "You gain energy from group conversations and enjoy collaborative brainstorming.", tipsForOthers: "Engage in group settings, build on their energy, and remember they may need social interaction to feel motivated.", tipsForSelf: "Notice when you're dominating airtime, create space for introverts, and practice one-on-one deep conversations.", extraversionMin: 70, ageTiers: "all" },
    { title: "The Selective Communicator", description: "You choose your moments to speak carefully and prefer meaningful exchanges over casual chat.", tipsForOthers: "Respect their silence, invite their input specifically, and value their contributions when they do speak up.", tipsForSelf: "Practice initiating conversation sometimes, share thoughts before they're perfectly formed, and engage in small talk as relationship building.", extraversionMax: 35, ageTiers: "all" },
    
    // Agreeableness-based Communication
    { title: "The Diplomatic Messenger", description: "You soften difficult messages and prioritize maintaining relationships even in conflict.", tipsForOthers: "Read between the lines, ask clarifying questions, and appreciate their effort to preserve harmony.", tipsForSelf: "Practice being more direct when needed, say what you mean (kindly), and don't sacrifice clarity for comfort.", agreeablenessMin: 65, ageTiers: "all" },
    { title: "The Candid Communicator", description: "You tell it like it is and value honesty over diplomacy. Your feedback is clear and unfiltered.", tipsForOthers: "Don't take bluntness personally, appreciate their honesty, and ask for elaboration if feedback seems harsh.", tipsForSelf: "Soften delivery without diluting message, check in on how your words land, and remember that kindness and honesty can coexist.", agreeablenessMax: 40, ageTiers: "all" },
    { title: "The Collaborative Communicator", description: "You seek consensus and ensure everyone's voice is heard before moving forward.", tipsForOthers: "Contribute your perspective, support group decisions, and appreciate their inclusive approach.", tipsForSelf: "Know when to move forward without full consensus, make decisions in time-sensitive situations, and balance inclusion with efficiency.", agreeablenessMin: 60, extraversionMin: 50, ageTiers: "all" },
    { title: "The Challenging Communicator", description: "You test ideas rigorously and aren't afraid to play devil's advocate for better outcomes.", tipsForOthers: "Separate challenge from criticism, engage with their counterpoints, and see pushback as care for quality.", tipsForSelf: "Balance challenge with affirmation, explain your intent to improve (not defeat), and know when consensus matters more than optimization.", agreeablenessMax: 45, ageTiers: "all" },
  ];

  for (const style of communicationStyleData) {
    await db.insert(communicationStyles).values(style).onConflictDoNothing();
  }
  console.log(`Inserted ${communicationStyleData.length} communication styles`);

  // 6. WORK ENVIRONMENTS (50+ entries)
  const workEnvironmentData = [
    // Innovation-focused
    { title: "The Startup Greenhouse", description: "Fast-paced, ambiguous, and full of possibility. You'll wear many hats and pivot frequently.", idealFor: "Highly open individuals who thrive on novelty and can handle uncertainty", challenges: "Lack of structure, unclear career paths, potential burnout", opennessMin: 65, conscientiousnessMax: 55, discStyles: "D,I", ageTiers: "young_adult,adult" },
    { title: "The Research Lab", description: "Deep intellectual work with freedom to explore. Collaboration with brilliant minds.", idealFor: "Curious introverts who love diving deep into complex problems", challenges: "Slow pace of change, academic politics, isolation potential", opennessMin: 60, extraversionMax: 50, ageTiers: "young_adult,adult" },
    { title: "The Creative Studio", description: "Artistic expression, unconventional hours, project-based work with fellow creatives.", idealFor: "Open, artistic individuals who need creative freedom", challenges: "Income instability, subjective feedback, intense competition", opennessMin: 65, ageTiers: "teen,young_adult,adult" },
    { title: "The Innovation Hub", description: "Corporate resources with startup mentality. R&D focus with some structure.", idealFor: "Creative minds who want stability but also innovation", challenges: "Bureaucratic constraints, competing priorities, slow decision-making", opennessMin: 60, conscientiousnessMin: 50, ageTiers: "young_adult,adult" },
    
    // Structure-focused
    { title: "The Corporate Tower", description: "Clear hierarchies, defined processes, predictable advancement paths.", idealFor: "Conscientious individuals who value stability and clear expectations", challenges: "Slow change, office politics, limited autonomy", conscientiousnessMin: 60, opennessMax: 50, discStyles: "C,S", ageTiers: "young_adult,adult" },
    { title: "The Government Agency", description: "Structured work with public service mission. Job security and benefits.", idealFor: "Detail-oriented individuals motivated by public good", challenges: "Bureaucracy, slow pace, limited flexibility", conscientiousnessMin: 55, ageTiers: "young_adult,adult" },
    { title: "The Law Firm", description: "Rigorous, competitive environment with clear metrics and high standards.", idealFor: "Highly conscientious individuals with attention to detail and stamina", challenges: "Long hours, high pressure, competitive culture", conscientiousnessMin: 70, extraversionMin: 45, ageTiers: "young_adult,adult" },
    { title: "The Financial Institution", description: "Data-driven, regulated environment with clear performance metrics.", idealFor: "Analytical minds who thrive with numbers and structure", challenges: "Regulatory pressure, market volatility stress, competitive culture", conscientiousnessMin: 65, discStyles: "D,C", ageTiers: "young_adult,adult" },
    
    // People-focused
    { title: "The Nonprofit Mission", description: "Purpose-driven work in service of a cause. Collaborative, values-aligned team.", idealFor: "Agreeable individuals motivated by making a difference", challenges: "Resource constraints, compassion fatigue, work-life blur", opennessMin: 50, extraversionMin: 50, ageTiers: "young_adult,adult" },
    { title: "The Healthcare Setting", description: "Patient-centered work with interdisciplinary teams. High emotional stakes.", idealFor: "Empathetic individuals who can handle emotional intensity", challenges: "Emotional burden, shift work, systemic frustrations", extraversionMin: 45, ageTiers: "young_adult,adult" },
    { title: "The Education Environment", description: "Development-focused work shaping young minds. Seasonal rhythms and community.", idealFor: "Patient, nurturing individuals who love learning and teaching", challenges: "Administrative burden, limited autonomy, emotional labor", opennessMin: 55, ageTiers: "young_adult,adult" },
    { title: "The Customer Success Hub", description: "Relationship-building focus with clear service goals. Solving problems for people.", idealFor: "Friendly, patient individuals who enjoy helping others succeed", challenges: "Difficult customers, repetitive issues, emotional labor", extraversionMin: 55, ageTiers: "young_adult,adult" },
    
    // Independence-focused
    { title: "The Freelance Life", description: "Total autonomy, varied projects, flexible schedule. You're the boss.", idealFor: "Self-motivated individuals who thrive without external structure", challenges: "Income uncertainty, isolation, self-marketing demands", conscientiousnessMin: 55, opennessMin: 55, ageTiers: "young_adult,adult" },
    { title: "The Remote-First Company", description: "Work from anywhere with digital-first communication. Results over presence.", idealFor: "Self-directed individuals who value flexibility and autonomy", challenges: "Communication barriers, loneliness, work-life boundary blur", conscientiousnessMin: 55, extraversionMax: 55, ageTiers: "young_adult,adult" },
    { title: "The Consulting Practice", description: "Varied clients, intellectually stimulating projects, expertise-based work.", idealFor: "Strategic thinkers who enjoy variety and building expertise", challenges: "Travel demands, client management, business development pressure", opennessMin: 55, conscientiousnessMin: 55, extraversionMin: 50, ageTiers: "adult" },
    { title: "The Solo Practice", description: "Complete independence in your professional domain. Build your own empire.", idealFor: "Highly self-motivated individuals with entrepreneurial drive", challenges: "Wearing all hats, isolation, full accountability", conscientiousnessMin: 60, ageTiers: "adult" },
    
    // Hands-on-focused  
    { title: "The Maker's Workshop", description: "Physical creation with tangible outputs. Craft-focused with immediate feedback.", idealFor: "Practical individuals who love working with their hands", challenges: "Physical demands, limited earning ceiling, specialized tools", opennessMin: 45, conscientiousnessMin: 55, ageTiers: "teen,young_adult,adult" },
    { title: "The Trade Shop", description: "Skilled labor with clear apprenticeship paths. Practical problem-solving daily.", idealFor: "Hands-on individuals who value mastery and tangible results", challenges: "Physical demands, weather exposure, early start times", conscientiousnessMin: 55, ageTiers: "teen,young_adult,adult" },
    { title: "The Field Station", description: "Outdoor work with nature or infrastructure. Physical activity and variety.", idealFor: "Active individuals who prefer movement to desk work", challenges: "Weather exposure, physical demands, remote locations", extraversionMax: 60, ageTiers: "teen,young_adult,adult" },
  ];

  for (const env of workEnvironmentData) {
    await db.insert(workEnvironments).values(env).onConflictDoNothing();
  }
  console.log(`Inserted ${workEnvironmentData.length} work environments`);

  // 7. RELATIONSHIP INSIGHTS (50+ entries)
  const relationshipInsightData = [
    // High Trait Insights
    { title: "The Curious Partner", description: "Your openness to new experiences keeps relationships fresh and exciting. You bring variety and intellectual depth.", strengthsInRelationships: "You introduce partners to new ideas, experiences, and perspectives. You're rarely boring and encourage growth.", growthAreas: "Ground flights of fancy with practical attention. Don't let the next new thing distract from nurturing what's here.", compatibilityNotes: "Best with those who appreciate novelty. May clash with those who crave routine stability.", primaryTrait: "O", primaryTraitMin: 65, ageTiers: "teen,young_adult,adult" },
    { title: "The Reliable Rock", description: "Your conscientiousness makes you a dependable, trustworthy partner who follows through on commitments.", strengthsInRelationships: "You're there when you say you'll be. You create stability and help partners feel secure.", growthAreas: "Loosen up sometimes—spontaneity can be romantic. Don't let your standards become judgment of your partner.", compatibilityNotes: "Great with those who value reliability. May frustrate spontaneous types.", primaryTrait: "C", primaryTraitMin: 65, ageTiers: "teen,young_adult,adult" },
    { title: "The Social Spark", description: "Your extraversion brings energy and connection to relationships. You enjoy shared activities and socializing together.", strengthsInRelationships: "You keep the relationship active and connected to a wider community. You express affection openly.", growthAreas: "Make space for quiet intimacy too. Ensure your partner has the recharge time they need.", compatibilityNotes: "Thrives with socially energetic partners. May overwhelm introverts if not careful.", primaryTrait: "E", primaryTraitMin: 65, ageTiers: "teen,young_adult,adult" },
    { title: "The Nurturing Heart", description: "Your high agreeableness means you prioritize harmony and your partner's wellbeing in the relationship.", strengthsInRelationships: "You create emotional safety. You're generous with support and quick to forgive.", growthAreas: "Don't lose yourself in serving others. Assert your needs too—healthy relationships require both voices.", compatibilityNotes: "Wonderful with most personalities. Watch for compatibility with very competitive or dominant types.", primaryTrait: "A", primaryTraitMin: 65, ageTiers: "teen,young_adult,adult" },
    { title: "The Grounded Anchor", description: "Your emotional stability provides a calm foundation for relationships even during turbulent times.", strengthsInRelationships: "You don't overreact. You provide steady reassurance and consistent emotional presence.", growthAreas: "Show vulnerability sometimes—emotional depth requires sharing your feelings too, even difficult ones.", compatibilityNotes: "Excellent for anxious partners. May seem distant to those who want more emotional expression.", primaryTrait: "N", primaryTraitMax: 35, ageTiers: "teen,young_adult,adult" },
    
    // Lower Trait Insights
    { title: "The Tradition Keeper", description: "Your preference for the familiar brings comfort and predictability to relationships.", strengthsInRelationships: "You're consistent and loyal. You honor commitments and build stable, enduring partnerships.", growthAreas: "Stay open to your partner's ideas for change. Growth requires stepping outside comfort zones together.", compatibilityNotes: "Best with stability-seekers. May conflict with highly adventurous partners.", primaryTrait: "O", primaryTraitMax: 40, ageTiers: "teen,young_adult,adult" },
    { title: "The Flexible Flow", description: "Your relaxed approach to planning brings spontaneity and adaptability to relationships.", strengthsInRelationships: "You go with the flow and don't sweat the small stuff. You're fun and easygoing.", growthAreas: "Follow through on commitments. Your partner may need more reliability than you naturally provide.", compatibilityNotes: "Great with relaxed partners. May frustrate those who need structure and planning.", primaryTrait: "C", primaryTraitMax: 40, ageTiers: "teen,young_adult,adult" },
    { title: "The Deep Diver", description: "Your introversion brings depth and intimacy to close relationships.", strengthsInRelationships: "You listen deeply and value quality connection over quantity. You're thoughtful and attentive.", growthAreas: "Initiate connection sometimes—don't always wait for your partner to reach out.", compatibilityNotes: "Ideal for fellow introverts or sensitive extraverts. May feel overwhelmed by highly social partners.", primaryTrait: "E", primaryTraitMax: 40, ageTiers: "teen,young_adult,adult" },
    { title: "The Honest Mirror", description: "Your directness brings clarity and authenticity to relationships.", strengthsInRelationships: "You say what you mean. Your partner always knows where they stand with you.", growthAreas: "Soften delivery without diluting message. Kindness and honesty aren't mutually exclusive.", compatibilityNotes: "Works well with direct types. May hurt more sensitive partners without intending to.", primaryTrait: "A", primaryTraitMax: 40, ageTiers: "teen,young_adult,adult" },
    { title: "The Feeling Deeply", description: "Your emotional sensitivity brings passion and depth to relationships.", strengthsInRelationships: "You feel things intensely, including love. Your emotions create rich, meaningful connections.", growthAreas: "Develop tools for managing emotional intensity. Your partner can't always fix your feelings.", compatibilityNotes: "Beautiful with emotionally available partners. May overwhelm more stoic types.", primaryTrait: "N", primaryTraitMin: 65, ageTiers: "teen,young_adult,adult" },
    
    // Combination Insights
    { title: "The Passionate Creator", description: "Your openness and emotional depth create intense, creative partnerships full of meaning.", strengthsInRelationships: "You bring imagination and emotional richness. Relationships with you are never dull.", growthAreas: "Balance emotional intensity with stability. Not every feeling needs to become a conversation.", compatibilityNotes: "Best with emotionally intelligent, creative partners.", primaryTrait: "O", primaryTraitMin: 60, neuroticismMin: 55, ageTiers: "young_adult,adult" },
    { title: "The Protective Guardian", description: "Your conscientiousness and emotional steadiness make you a reliable protector of the relationship.", strengthsInRelationships: "You create security through both action and emotional presence. You're the calm in any storm.", growthAreas: "Allow room for imperfection—in yourself and your partner. Control isn't the same as care.", compatibilityNotes: "Ideal for those who need stability and structure.", primaryTrait: "C", primaryTraitMin: 60, neuroticismMax: 40, ageTiers: "young_adult,adult" },
    { title: "The Charismatic Connector", description: "Your extraversion and agreeableness make you a warm, socially skilled partner.", strengthsInRelationships: "You navigate social situations smoothly, making your partner feel proud and included.", growthAreas: "Ensure one-on-one time is truly intimate, not just performative. Deep connection requires slowing down.", compatibilityNotes: "Wonderful with social partners. May overwhelm private individuals.", primaryTrait: "E", primaryTraitMin: 60, agreeablenessMin: 55, ageTiers: "teen,young_adult,adult" },
    { title: "The Thoughtful Introvert", description: "Your combination of introversion and agreeableness creates gentle, thoughtful partnership.", strengthsInRelationships: "You listen deeply, consider carefully, and prioritize your partner's wellbeing.", growthAreas: "Speak up about your needs. Don't let your quietness become invisible resentment.", compatibilityNotes: "Perfect for those who value peace and depth over excitement.", primaryTrait: "E", primaryTraitMax: 40, agreeablenessMin: 55, ageTiers: "teen,young_adult,adult" },
  ];

  for (const insight of relationshipInsightData) {
    await db.insert(relationshipInsights).values(insight).onConflictDoNothing();
  }
  console.log(`Inserted ${relationshipInsightData.length} relationship insights`);

  // 8. CAREER PATHS (100+ entries)
  const careerPathData = [
    // High Openness Careers
    { title: "User Experience Designer", description: "Shape how people interact with digital products. Blend psychology, design, and technology.", salaryRange: "$70K-150K", growthOutlook: "High", educationReq: "Degree", primaryTrait: "O", primaryTraitMin: 60, secondaryTrait: "C", secondaryTraitMin: 50, mbtiTypes: "INFP,ENFP,INFJ,INTJ", discStyles: "I,C", industry: "Tech", ageTiers: "young_adult,adult" },
    { title: "Product Manager", description: "Lead the vision for digital products. Balance user needs with business goals.", salaryRange: "$90K-180K", growthOutlook: "High", educationReq: "Degree", primaryTrait: "O", primaryTraitMin: 55, secondaryTrait: "E", secondaryTraitMin: 50, mbtiTypes: "ENTP,ENTJ,ENFJ,INTJ", discStyles: "D,I", industry: "Tech", ageTiers: "young_adult,adult" },
    { title: "Creative Director", description: "Lead creative teams and shape brand identities. Set the artistic vision.", salaryRange: "$100K-200K", growthOutlook: "Moderate", educationReq: "Degree", primaryTrait: "O", primaryTraitMin: 70, secondaryTrait: "E", secondaryTraitMin: 50, mbtiTypes: "ENFP,ENTP,ENTJ", discStyles: "D,I", industry: "Creative", ageTiers: "adult" },
    { title: "Architect", description: "Design buildings and spaces that inspire. Blend art, engineering, and functionality.", salaryRange: "$80K-150K", growthOutlook: "Moderate", educationReq: "Degree", primaryTrait: "O", primaryTraitMin: 60, secondaryTrait: "C", secondaryTraitMin: 60, mbtiTypes: "INTJ,INFJ,INTP,ENTJ", discStyles: "C", industry: "Creative", ageTiers: "young_adult,adult" },
    { title: "Research Scientist", description: "Push the boundaries of human knowledge. Explore questions no one has answered.", salaryRange: "$70K-150K", growthOutlook: "Moderate", educationReq: "Degree", primaryTrait: "O", primaryTraitMin: 65, secondaryTrait: "C", secondaryTraitMin: 55, mbtiTypes: "INTP,INTJ,ENTP,INFJ", discStyles: "C", industry: "Science", ageTiers: "young_adult,adult" },
    { title: "Documentary Filmmaker", description: "Tell stories that matter. Capture reality and share it with the world.", salaryRange: "$40K-120K", growthOutlook: "Moderate", educationReq: "Certificate", primaryTrait: "O", primaryTraitMin: 65, mbtiTypes: "INFP,ENFP,INFJ,ISFP", discStyles: "I,S", industry: "Media", ageTiers: "young_adult,adult" },
    { title: "Strategy Consultant", description: "Solve complex business problems for leading organizations.", salaryRange: "$90K-200K", growthOutlook: "High", educationReq: "Degree", primaryTrait: "O", primaryTraitMin: 60, secondaryTrait: "C", secondaryTraitMin: 60, mbtiTypes: "INTJ,ENTJ,ENTP,INTP", discStyles: "D,C", industry: "Consulting", ageTiers: "young_adult,adult" },
    { title: "Game Designer", description: "Create interactive experiences that entertain and engage millions.", salaryRange: "$60K-130K", growthOutlook: "High", educationReq: "Certificate", primaryTrait: "O", primaryTraitMin: 65, secondaryTrait: "C", secondaryTraitMin: 50, mbtiTypes: "INTP,ENTP,INFP,ENFP", discStyles: "I,C", industry: "Gaming", ageTiers: "teen,young_adult,adult" },
    
    // High Conscientiousness Careers
    { title: "Financial Analyst", description: "Analyze data to guide investment decisions and business strategy.", salaryRange: "$65K-130K", growthOutlook: "Moderate", educationReq: "Degree", primaryTrait: "C", primaryTraitMin: 65, mbtiTypes: "ISTJ,INTJ,ESTJ,ENTJ", discStyles: "C,D", industry: "Finance", ageTiers: "young_adult,adult" },
    { title: "Project Manager", description: "Lead teams to deliver complex projects on time and budget.", salaryRange: "$70K-140K", growthOutlook: "High", educationReq: "Certificate", primaryTrait: "C", primaryTraitMin: 65, secondaryTrait: "E", secondaryTraitMin: 45, mbtiTypes: "ESTJ,ENTJ,ISTJ,ENFJ", discStyles: "D,C", industry: "Tech", ageTiers: "young_adult,adult" },
    { title: "Accountant", description: "Ensure financial accuracy and compliance for organizations.", salaryRange: "$55K-110K", growthOutlook: "Stable", educationReq: "Degree", primaryTrait: "C", primaryTraitMin: 70, mbtiTypes: "ISTJ,ISFJ,ESTJ", discStyles: "C,S", industry: "Finance", ageTiers: "young_adult,adult" },
    { title: "Quality Assurance Engineer", description: "Ensure software products meet quality standards before release.", salaryRange: "$60K-120K", growthOutlook: "High", educationReq: "Certificate", primaryTrait: "C", primaryTraitMin: 65, mbtiTypes: "ISTJ,INTJ,ISTP,INTP", discStyles: "C", industry: "Tech", ageTiers: "young_adult,adult" },
    { title: "Operations Manager", description: "Optimize business operations for efficiency and effectiveness.", salaryRange: "$65K-130K", growthOutlook: "Moderate", educationReq: "Degree", primaryTrait: "C", primaryTraitMin: 65, secondaryTrait: "E", secondaryTraitMin: 45, mbtiTypes: "ESTJ,ENTJ,ISTJ,ENFJ", discStyles: "D,C", industry: "Business", ageTiers: "adult" },
    { title: "Data Analyst", description: "Extract insights from data to drive business decisions.", salaryRange: "$55K-110K", growthOutlook: "High", educationReq: "Degree", primaryTrait: "C", primaryTraitMin: 60, secondaryTrait: "O", secondaryTraitMin: 50, mbtiTypes: "INTJ,INTP,ISTJ,ENTJ", discStyles: "C", industry: "Tech", ageTiers: "young_adult,adult" },
    { title: "Supply Chain Manager", description: "Coordinate the flow of goods from production to consumer.", salaryRange: "$70K-140K", growthOutlook: "Moderate", educationReq: "Degree", primaryTrait: "C", primaryTraitMin: 65, mbtiTypes: "ESTJ,ISTJ,ENTJ,INTJ", discStyles: "D,C", industry: "Logistics", ageTiers: "adult" },
    { title: "Surgeon", description: "Perform complex medical procedures with precision and care.", salaryRange: "$300K-500K", growthOutlook: "Stable", educationReq: "Degree", primaryTrait: "C", primaryTraitMin: 75, mbtiTypes: "ISTJ,INTJ,ISTP,ENTJ", discStyles: "D,C", industry: "Healthcare", ageTiers: "adult" },
    
    // High Extraversion Careers
    { title: "Sales Director", description: "Lead sales teams and drive revenue growth for organizations.", salaryRange: "$100K-250K", growthOutlook: "Moderate", educationReq: "Degree", primaryTrait: "E", primaryTraitMin: 65, secondaryTrait: "C", secondaryTraitMin: 50, mbtiTypes: "ESTP,ENTJ,ENFJ,ESFJ", discStyles: "D,I", industry: "Sales", ageTiers: "adult" },
    { title: "Public Relations Manager", description: "Shape public perception and manage communications for organizations.", salaryRange: "$65K-130K", growthOutlook: "Moderate", educationReq: "Degree", primaryTrait: "E", primaryTraitMin: 60, secondaryTrait: "A", secondaryTraitMin: 55, mbtiTypes: "ENFJ,ESFJ,ENFP,ENTJ", discStyles: "I,D", industry: "Marketing", ageTiers: "young_adult,adult" },
    { title: "Human Resources Director", description: "Lead people strategy and culture for organizations.", salaryRange: "$90K-180K", growthOutlook: "Moderate", educationReq: "Degree", primaryTrait: "E", primaryTraitMin: 55, secondaryTrait: "A", secondaryTraitMin: 60, mbtiTypes: "ENFJ,ESFJ,ENFP,ENTJ", discStyles: "I,S", industry: "HR", ageTiers: "adult" },
    { title: "Event Planner", description: "Create memorable experiences through events and gatherings.", salaryRange: "$50K-100K", growthOutlook: "Moderate", educationReq: "Certificate", primaryTrait: "E", primaryTraitMin: 60, secondaryTrait: "C", secondaryTraitMin: 55, mbtiTypes: "ESFJ,ENFJ,ESFP,ENFP", discStyles: "I,S", industry: "Events", ageTiers: "young_adult,adult" },
    { title: "Real Estate Broker", description: "Help people find homes and navigate property transactions.", salaryRange: "$50K-200K", growthOutlook: "Moderate", educationReq: "Certificate", primaryTrait: "E", primaryTraitMin: 60, mbtiTypes: "ESTP,ESFP,ENTJ,ENFJ", discStyles: "D,I", industry: "Real Estate", ageTiers: "young_adult,adult" },
    { title: "Corporate Trainer", description: "Develop and deliver training programs for organizations.", salaryRange: "$60K-120K", growthOutlook: "Moderate", educationReq: "Degree", primaryTrait: "E", primaryTraitMin: 60, secondaryTrait: "A", secondaryTraitMin: 55, mbtiTypes: "ENFJ,ESFJ,ENTJ,ENFP", discStyles: "I,D", industry: "Education", ageTiers: "adult" },
    { title: "Talent Agent", description: "Represent and promote artists, athletes, or entertainers.", salaryRange: "$60K-200K", growthOutlook: "Moderate", educationReq: "None", primaryTrait: "E", primaryTraitMin: 65, secondaryTrait: "C", secondaryTraitMin: 50, mbtiTypes: "ESTP,ENTJ,ENTP,ENFJ", discStyles: "D,I", industry: "Entertainment", ageTiers: "adult" },
    { title: "News Anchor", description: "Deliver news and information to audiences through broadcast media.", salaryRange: "$50K-150K", growthOutlook: "Stable", educationReq: "Degree", primaryTrait: "E", primaryTraitMin: 65, mbtiTypes: "ENFJ,ESFJ,ENTJ,ESTJ", discStyles: "I,D", industry: "Media", ageTiers: "young_adult,adult" },
    
    // High Agreeableness Careers
    { title: "Counselor/Therapist", description: "Help individuals navigate mental health challenges and life transitions.", salaryRange: "$50K-100K", growthOutlook: "High", educationReq: "Degree", primaryTrait: "A", primaryTraitMin: 70, mbtiTypes: "INFJ,ENFJ,INFP,ISFJ", discStyles: "S,I", industry: "Healthcare", ageTiers: "adult" },
    { title: "Social Worker", description: "Support individuals and families through challenging circumstances.", salaryRange: "$45K-80K", growthOutlook: "High", educationReq: "Degree", primaryTrait: "A", primaryTraitMin: 65, mbtiTypes: "INFJ,ENFJ,ISFJ,ESFJ", discStyles: "S,I", industry: "Social Services", ageTiers: "young_adult,adult" },
    { title: "Teacher", description: "Educate and inspire the next generation of learners.", salaryRange: "$45K-80K", growthOutlook: "Stable", educationReq: "Degree", primaryTrait: "A", primaryTraitMin: 60, secondaryTrait: "E", secondaryTraitMin: 45, mbtiTypes: "ENFJ,ESFJ,INFJ,ISFJ", discStyles: "S,I", industry: "Education", ageTiers: "young_adult,adult" },
    { title: "Nurse", description: "Provide direct patient care and support in healthcare settings.", salaryRange: "$60K-110K", growthOutlook: "High", educationReq: "Degree", primaryTrait: "A", primaryTraitMin: 60, secondaryTrait: "C", secondaryTraitMin: 55, mbtiTypes: "ISFJ,ESFJ,INFJ,ENFJ", discStyles: "S,C", industry: "Healthcare", ageTiers: "young_adult,adult" },
    { title: "Nonprofit Director", description: "Lead mission-driven organizations making positive social impact.", salaryRange: "$60K-150K", growthOutlook: "Moderate", educationReq: "Degree", primaryTrait: "A", primaryTraitMin: 65, secondaryTrait: "E", secondaryTraitMin: 55, mbtiTypes: "ENFJ,INFJ,ENTJ,ENFP", discStyles: "I,D", industry: "Nonprofit", ageTiers: "adult" },
    { title: "Veterinarian", description: "Care for animals and support their health and wellbeing.", salaryRange: "$80K-150K", growthOutlook: "High", educationReq: "Degree", primaryTrait: "A", primaryTraitMin: 65, secondaryTrait: "C", secondaryTraitMin: 60, mbtiTypes: "ISFJ,ISTJ,INFJ,ISFP", discStyles: "S,C", industry: "Healthcare", ageTiers: "young_adult,adult" },
    { title: "Mediator", description: "Facilitate resolution of conflicts between parties.", salaryRange: "$50K-100K", growthOutlook: "Moderate", educationReq: "Certificate", primaryTrait: "A", primaryTraitMin: 70, mbtiTypes: "INFJ,ENFJ,INFP,ISFJ", discStyles: "S", industry: "Legal", ageTiers: "adult" },
    { title: "Occupational Therapist", description: "Help people develop skills for daily living and work.", salaryRange: "$70K-100K", growthOutlook: "High", educationReq: "Degree", primaryTrait: "A", primaryTraitMin: 65, mbtiTypes: "ISFJ,ESFJ,INFJ,ENFJ", discStyles: "S,I", industry: "Healthcare", ageTiers: "young_adult,adult" },
  ];

  for (const career of careerPathData) {
    await db.insert(careerPaths).values(career).onConflictDoNothing();
  }
  console.log(`Inserted ${careerPathData.length} career paths`);

  console.log("Premium insights seeding complete!");
}
