'use client';

import Link from "next/link";
import { ArrowLeft, ChevronDown } from "lucide-react";
import { useState } from "react";

const FAQ_ITEMS = [
  {
    question: "What is KnowYouRole?",
    answer: "KnowYouRole is a free personality and career-reflection platform that combines a Big Five trait backbone with MBTI-style patterns and DISC-style communication language. It helps you understand your tendencies and explore possible career directions without pretending a quiz can define your whole identity. It is currently tailored for teens, young adults, and adults."
  },
  {
    question: "Is KnowYouRole really free?",
    answer: "Yes! The core personality assessments and career matching features are completely free, with no sign-up required to get started. We offer optional premium features for deeper insights, but the essential experience costs nothing."
  },
  {
    question: "How long does the assessment take?",
    answer: "Most users complete the assessment in ~5 minutes. The questions are designed to be quick and intuitive — just pick what feels most true most often. There are no trick questions or wrong answers."
  },
  {
    question: "How accurate is the assessment?",
    answer: "Your result reflects patterns in your answers, not a perfect measurement of your identity. Big Five gives the strongest research-backed trait layer; MBTI-style and DISC-style outputs are used as practical language for reflection and communication. Taking the quiz when you're in a typical mood, not extremely stressed or excited, tends to produce the most useful result."
  },
  {
    question: "Is it safe for teens?",
    answer: "Yes. The teen experience uses age-appropriate language and positive framing focused on strengths, communication, and self-understanding. We do not knowingly collect personal information from children under 13 without parental consent."
  },
  {
    question: "What personality frameworks do you use?",
    answer: "We use three complementary layers: Big Five traits as the research-backed backbone; MBTI-style patterns as memorable personality language; and DISC-style categories for communication and work-style reflection. The point is useful self-understanding, not forcing you into a permanent box."
  },
  {
    question: "Can I retake the assessment?",
    answer: "Yes, you can retake the assessment anytime. Personality can shift based on mood, life stage, and personal growth, so retaking it periodically can reveal how you're evolving."
  },
  {
    question: "Do I need to create an account?",
    answer: "Quiz completion data is saved securely so we can generate, recover, and improve results. You can still take the quiz without creating an account. Creating an account, when enabled, can add long-term history and comparison features."
  },
  {
    question: "How is my data handled?",
    answer: "Quiz completions are saved securely so your result can be generated, recovered, and improved. We do not sell your quiz results. Optional analytics and future advertising settings are controlled through cookie preferences where practical. See our Privacy Policy for details."
  },
  {
    question: "What are the career matches based on?",
    answer: "Career matches are generated by mapping your Big Five trait shape, MBTI-style pattern, DISC-style work style, and answer evidence to role profiles. Treat them as directions to test with projects, shadowing, classes, or interviews — not as a hiring prediction or life sentence."
  },
  {
    question: "Why do my results change when I retake the quiz?",
    answer: "Personality isn't fixed — it can shift based on your mood, recent experiences, and personal growth. Small variations between sessions are normal and expected. If you notice large swings, it could mean you were in a very different headspace. For the most consistent results, take the quiz when you're in a typical day-to-day mood."
  },
  {
    question: "What happens to my results if I don't create an account?",
    answer: "Your results are saved securely after quiz completion so your profile can be generated, recovered, and improved. If you want long-term history or comparison features, create an account when that option is available."
  },
];

function FaqItem({ question, answer }: { question: string; answer: string }) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="border-b border-warm-gray/10 dark:border-[#A78BFA]/10">
      <button
        onClick={() => setIsOpen(!isOpen)}
        aria-expanded={isOpen}
        aria-controls={`faq-answer-${question.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 30)}`}
        className="w-full flex items-center justify-between py-4 text-left"
        data-testid={`button-faq-${question.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 30)}`}
      >
        <span className="font-medium text-warm-gray dark:text-[#F8FAFC] pr-4">{question}</span>
        <ChevronDown className={`w-5 h-5 text-warm-gray/50 dark:text-[#94A3B8] flex-shrink-0 transition-transform ${isOpen ? "rotate-180" : ""}`} />
      </button>
      {isOpen && (
        <p id={`faq-answer-${question.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 30)}`} className="pb-4 text-sm text-warm-gray/70 dark:text-[#94A3B8] leading-relaxed">
          {answer}
        </p>
      )}
    </div>
  );
}

export default function Faq() {
  return (
    <div className="min-h-screen bg-soft-cream dark:bg-[#0A0A12] text-warm-gray dark:text-[#F8FAFC]">
      <header className="sticky top-0 z-50 px-6 py-4 bg-soft-cream/90 dark:bg-[#0A0A12]/90 backdrop-blur-sm border-b border-warm-gray/10 dark:border-[#A78BFA]/10">
        <div className="max-w-2xl mx-auto flex items-center gap-3">
          <Link href="/" className="flex items-center gap-2 text-sm text-warm-gray/70 dark:text-[#94A3B8] hover:text-terracotta dark:hover:text-[#A78BFA] transition-colors" data-testid="link-back-home">
              <ArrowLeft className="w-4 h-4" />
              Back to Home
          </Link>
        </div>
      </header>

      <main className="max-w-2xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-display font-bold mb-2" data-testid="text-faq-title">Frequently Asked Questions</h1>
        <p className="text-warm-gray/60 dark:text-[#94A3B8] mb-8">Everything you need to know about KnowYouRole</p>

        <div className="space-y-0">
          {FAQ_ITEMS.map((item) => (
            <FaqItem key={item.question} question={item.question} answer={item.answer} />
          ))}
        </div>
      </main>
    </div>
  );
}
